const ALLOWED_KINDS=new Set(['question','suggestion']);
const clean=(v,max=1500)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);
const validStudentId=id=>/^[a-zA-Z0-9-]{20,80}$/.test(String(id||''));
function env(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw Object.assign(new Error('Support database is not configured'),{status:503});return{url:url.replace(/\/$/,''),key}}
async function supabase(path,options={}){const {url,key}=env();const r=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok){const e=new Error(data?.message||data?.error||'Database request failed');e.status=r.status;e.detail=data;throw e}return data}
function sendError(res,err){const status=Number(err?.status)||500;res.status(status).json({error:status>=500?'Қолдау қызметі уақытша қолжетімсіз. Кейінірек қайталап көріңіз.':err.message||'Сұраныс орындалмады.'})}
async function notifyTelegram(ticket){const token=process.env.TELEGRAM_BOT_TOKEN,chatId=process.env.TELEGRAM_CHAT_ID;if(!token||!chatId)return;const kind=ticket.kind==='suggestion'?'Ұсыныс':'Сұрақ';const text=`🔔 JUZDEREK — жаңа ${kind.toLowerCase()}\n\nОқушы: ${ticket.username}\nБет: ${ticket.page||'-'}\n\n${ticket.message}`.slice(0,3900);try{await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:chatId,text,disable_web_page_preview:true})})}catch{}
}
function requireAdmin(req){const expected=process.env.SUPPORT_ADMIN_TOKEN;if(!expected)throw Object.assign(new Error('Admin access is not configured'),{status:503});const auth=String(req.headers.authorization||'');if(auth!==`Bearer ${expected}`)throw Object.assign(new Error('Рұқсат жоқ'),{status:401})}
module.exports={ALLOWED_KINDS,clean,validStudentId,supabase,sendError,notifyTelegram,requireAdmin};