alter table public.student_analytics add column if not exists friend_code text;

update public.student_analytics
set friend_code = 'JZ-' || upper(substr(md5(student_id), 1, 8))
where friend_code is null;

create unique index if not exists student_analytics_friend_code_uidx
  on public.student_analytics(friend_code)
  where friend_code is not null;

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id text not null,
  addressee_id text not null,
  status text not null default 'pending' check (status in ('pending','accepted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> addressee_id)
);

create unique index if not exists friendships_pair_uidx
  on public.friendships (least(requester_id, addressee_id), greatest(requester_id, addressee_id));
create index if not exists friendships_requester_idx on public.friendships(requester_id, status);
create index if not exists friendships_addressee_idx on public.friendships(addressee_id, status);
