(()=>{if(window.__JUZ_ACH_SYSTEM_LOADED)return;window.__JUZ_ACH_SYSTEM_LOADED=true;const A=[
{id:'aim',n:'Мерген',d:'100 дұрыс жауап жина.',r:'rare',target:100,type:'correct',img:'achievement-archer.webp'},
{id:'first',n:'Алғашқы қадам',d:'Алғашқы тақырыпты 100% толық меңгер.',r:'rare',target:1,type:'topics',img:'achievement-first-step.webp'},
{id:'scholar',n:'Білімпаз',d:'5 тақырыпты толық меңгер.',r:'rare',target:5,type:'topics',img:'achievement-scholar.webp'},
{id:'steady',n:'Тұрақтылық',d:'7 күндік streak жаса.',r:'rare',target:7,type:'streak',img:'achievement-streak.webp'},
{id:'knower',n:'Тарих білгірі',d:'15 тақырыпты толық меңгер.',r:'epic',target:15,type:'topics',img:'achievement-history-master.webp'},
{id:'determined',n:'Қайсар',d:'25 ойынды толық аяқта.',r:'rare',target:25,type:'games',img:'achievement-determined.webp'},
{id:'heart',n:'Жүректі жеңімпаз',d:'50 ойынды толық аяқта.',r:'epic',target:50,type:'games',img:'achievement-heart.webp'},
{id:'champion',n:'Жеңімпаз',d:'Бір тестті 100% нәтижемен аяқта.',r:'epic',target:1,type:'perfect',img:'achievement-champion.webp'},
{id:'explorer',n:'Зерттеуші',d:'30 тақырыпты толық меңгер.',r:'epic',target:30,type:'topics',img:'achievement-explorer.webp'},
{id:'consistency',n:'Жоспарлаушы',d:'14 күндік streak жаса.',r:'epic',target:14,type:'streak',img:'achievement-consistency.webp'},
{id:'streakMaster',n:'Streak шебері',d:'30 күндік streak жаса.',r:'legendary',target:30,type:'streak',img:'achievement-streak-master.webp'},
{id:'fast',n:'Жылдам жауап',d:'250 дұрыс жауап жина.',r:'rare',target:250,type:'correct',img:'achievement-fast-answer.webp'},
{id:'perfectSeries',n:'Қатесіз серия',d:'3 ойынды 100% нәтижемен аяқта.',r:'epic',target:3,type:'perfectCount',img:'achievement-perfect-streak.webp'},
{id:'eraTraveler',n:'Дәуір саяхатшысы',d:'40 тақырыпты толық меңгер.',r:'epic',target:40,type:'topics',img:'achievement-era-traveler.webp'},
{id:'personMaster',n:'Тұлғалар білгірі',d:'500 дұрыс жауап жина.',r:'epic',target:500,type:'correct',img:'achievement-person-master.webp'},
{id:'chronoMaster',n:'Хронология шебері',d:'100 ойынды толық аяқта.',r:'epic',target:100,type:'games',img:'achievement-chronology-master.webp'},
{id:'cardMaster',n:'Карточка шебері',d:'150 ойынды толық аяқта.',r:'legendary',target:150,type:'games',img:'achievement-card-master.webp'},
{id:'xpCollector',n:'XP коллекционері',d:'10 000 XP жина.',r:'legendary',target:10000,type:'xp',img:'achievement-xp-collector.webp'},
{id:'topics100',n:'100 тақырып',d:'100 тақырыпты толық меңгер.',r:'legendary',target:100,type:'topics',img:'achievement-100-topics.webp'},
{id:'legend',n:'JUZDEREK аңызы',d:'20 000 XP жинап, аңыз деңгейіне жет.',r:'legendary',target:20000,type:'xp',img:'achievement-juzderek-legend.webp'}
];
const IDS=new Set(A.map(a=>a.id)),MODES=new Set(['cards','quiz','person','chrono']);
const onTracker=()=>((location.pathname.split('/').pop()||'').toLowerCase()==='tracker.html');
const safeNum=(v,max=10000000)=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(max,n)):0};
function state(){let gp={},tp={},lm={};try{const a=JSON.parse(localStorage.getItem('juzderek_game_progress')||'{}'),b=JSON.parse(localStorage.getItem('juzderek_topics_progress')||'{}'),c=JSON.parse(localStorage.getItem('juzderek_learning_meta')||'{}');gp=a&&typeof a==='object'&&!Array.isArray(a)?a:{};tp=b&&typeof b==='object'&&!Array.isArray(b)?b:{};lm=c&&typeof c==='object'&&!Array.isArray(c)?c:{}}catch{}const vals=Object.values(tp).filter(t=>t&&typeof t==='object'&&!Array.isArray(t)),full=vals.filter(t=>Array.isArray(t.completed)&&new Set(t.completed.filter(m=>MODES.has(m))).size>=4).length,games=vals.reduce((n,t)=>n+(Array.isArray(t.completed)?new Set(t.completed.filter(m=>MODES.has(m))).size:0),0),scoreRows=vals.flatMap(t=>t.scores&&typeof t.scores==='object'&&!Array.isArray(t.scores)?Object.values(t.scores):[]).filter(s=>s&&typeof s==='object'),perfectCount=scoreRows.filter(s=>safeNum(s.pct,100)===100).length,avgPct=scoreRows.length?Math.round(scoreRows.reduce((n,s)=>n+safeNum(s.pct,100),0)/scoreRows.length):0;return{xp:safeNum(gp.xp),correct:safeNum(gp.correct),streak:safeNum(lm.streak,36500),games:safeNum(games,100000),perfect:perfectCount?1:0,perfectCount:safeNum(perfectCount,100000),topics:safeNum(full,10000),avgPct:safeNum(avgPct,100)}}
function val(a,s){return safeNum(s[a.type])}function unlocked(a,s){return val(a,s)>=a.target}function ensureUI(){if(onTracker()||document.getElementById('achievementUnlock'))return;document.body.insertAdjacentHTML('beforeend','<div class="confetti-layer" id="confettiLayer"></div><div class="unlock-backdrop" id="achievementUnlock"><div class="unlock-card"><span class="unlock-kicker">ЖАҢА ЖЕТІСТІК АШЫЛДЫ!</span><div class="unlock-badge"><img id="unlockIcon" src="./assets/achievement-archer.webp" alt=""></div><h2 id="unlockTitle"></h2><p id="unlockText"></p><div class="unlock-actions"><button class="secondary" id="unlockContinue">Жалғастыру</button><button class="primary" id="unlockView">Жетістікті көру</button></div></div></div>');document.getElementById('unlockContinue').onclick=()=>document.getElementById('achievementUnlock').classList.remove('show');document.getElementById('unlockView').onclick=()=>location.href='achievements.html'}
function confetti(){const layer=document.getElementById('confettiLayer');if(!layer)return;layer.innerHTML='';for(let i=0;i<28;i++){const p=document.createElement('i');p.className='confetti-piece';const a=Math.PI*2*i/28+(Math.random()*.28-.14),d=150+Math.random()*190,x=Math.cos(a)*d,y=Math.sin(a)*d-45;p.style.setProperty('--x',x+'px');p.style.setProperty('--y',y+'px');p.style.setProperty('--x2',x*1.08+'px');p.style.setProperty('--y2',y+110+'px');p.style.setProperty('--r',(180+Math.random()*480)+'deg');p.style.setProperty('--r2',(540+Math.random()*720)+'deg');layer.appendChild(p)}setTimeout(()=>layer.innerHTML='',1300)}
function check(show=true){const s=state();let seen=[];try{const raw=JSON.parse(localStorage.getItem('juzderek_seen_achievements')||'[]');seen=Array.isArray(raw)?[...new Set(raw.filter(id=>typeof id==='string'&&IDS.has(id)))]:[]}catch{}const newly=A.filter(a=>unlocked(a,s)&&!seen.includes(a.id));if(newly.length&&show&&!onTracker()){ensureUI();const a=newly[0],ui=document.getElementById('achievementUnlock');if(ui){document.getElementById('unlockTitle').textContent=a.n;document.getElementById('unlockText').textContent=a.d;document.getElementById('unlockIcon').src='./assets/'+a.img;ui.classList.add('show');confetti();seen.push(a.id);localStorage.setItem('juzderek_seen_achievements',JSON.stringify(seen.slice(0,A.length)))}}window.dispatchEvent(new CustomEvent('juzderek:achievements',{detail:{state:s,items:A}}))}
const native=localStorage.setItem.bind(localStorage);localStorage.setItem=function(k,v){native(k,v);if(['juzderek_game_progress','juzderek_topics_progress','juzderek_learning_meta'].includes(k))setTimeout(()=>check(true),0)};window.JUZ_ACHIEVEMENTS=A;window.JUZ_ACH_STATE=state;window.JUZ_CHECK_ACHIEVEMENTS=check;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{ensureUI();check(false)});else{ensureUI();check(false)}})();