const icons={
 temple:'<svg viewBox="0 0 24 24"><path d="M3 10h18M5 10V7l7-4 7 4v3M6 10v8M10 10v8M14 10v8M18 10v8M4 18h16M3 21h18"/></svg>',
 shield:'<svg viewBox="0 0 24 24"><path d="M12 3 5 6v5c0 4.7 2.8 8 7 10 4.2-2 7-5.3 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-5"/></svg>',
 book:'<svg viewBox="0 0 24 24"><path d="M4 5.5A3.5 3.5 0 0 1 7.5 2H20v17H7.5A3.5 3.5 0 0 0 4 22V5.5Z"/><path d="M4 18.5A3.5 3.5 0 0 1 7.5 15H20"/></svg>',
 globe:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/></svg>'
};

document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icons[el.dataset.icon]||'');

const periodData={
 ancient:{title:'Ежелгі заман',icon:'temple',description:'Ежелгі өркениеттер, мемлекеттер, діндер мен философиялық ілімдер.',topics:['Ежелгі Египет','Ежелгі Қосөзен','Ежелгі Қытай','Ежелгі Үндістан','Ежелгі Парсы мемлекеті','Ежелгі Грекия өркениеті','Александр Македонскийдің империясы','Ежелгі Рим өркениеті','Рим империясы','Ежелгі діни нанымдар','Көне философиялық ілімдер','Әлемдік діндер мен өркениеттердің дамуы']},
 medieval:{title:'Орта ғасыр',icon:'shield',description:'Феодалдық қоғамнан Қайта өрлеу мен Реформацияға дейінгі кезең.',topics:['Орта ғасырлар түсінігі','Феодалдық қоғам','Ортағасырлық қалалар мен өнер','Халықтардың Ұлы қоныс аударуы және Батыс Рим империясының құлауы','Византия империясы','Киев Русі','Ислам дінінің пайда болуы','Араб халифаты және мұсылман әлемі','Крест жорықтары','Шыңғыс хан','Моңғол империясы','Моңғолдардың әскери өнері','Әмір Темір мемлекеті','Мәскеу мемлекеті','Құбылай мемлекеті және Ильханат','Франция мен Англиядағы шаруалар көтерілісі','Феодалдық соғыстар','Жанна д’Арк','Еуропадағы орталықтанған мемлекеттер','Абсолютизм','Осман империясы','Ұлы Жібек жолы','Ұлы географиялық ашылулар','Реформация','Қайта өрлеу дәуірі','Гуманизм','Шығыстың ортағасырлық мәдениеті']},
 modern:{title:'Жаңа заман',icon:'book',description:'XVII–XIX ғасырлардағы революциялар, индустриялану, империялар мен жаңа саяси идеялар.',topics:['Жаңа заман дәуірі туралы түсінік','Өнеркәсіп төңкерісі және индустриалды қоғам','Ағартушылық дәуірі','XVII ғасырдағы ағылшын революциясы','АҚШ-тың құрылуы және Тәуелсіздік үшін соғыс','Француз революциясы','Наполеон дәуірі','Ресей империясының қалыптасуы','XVII–XVIII ғасырлардағы Үндістан','Еуропалық отаршылдық саясаты','Танзимат реформалары','Қырым соғысы','Апиын соғыстары','1848 жылғы Еуропа революциялары','Германия мен Италияның бірігуі','АҚШ-тағы азамат соғысы','Жапонияның ашылуы','Сипайлар көтерілісі','Үнді Ұлттық Конгресі','XIX ғасырдағы ғылым мен мәдениет']},
 contemporary:{title:'Қазіргі заман',icon:'globe',description:'XX–XXI ғасырлар: дүниежүзілік соғыстар, халықаралық қатынастар, жаһандану және технологиялар.',topics:['Қазіргі заман ұғымы және оның ерекшеліктері','Бірінші дүниежүзілік соғыс','Версаль–Вашингтон жүйесі','Мұстафа Кемал Ататүрік және Түркия','Махатма Ганди және Үндістан','XX ғасырдағы Қытай','XX ғасырдағы Жапония','1917 жылғы Ресей революциясы','КСРО-ның құрылуы','Ұлы экономикалық дағдарыс','Ф.Д. Рузвельттің Жаңа бағыты','Фашизм және тоталитарлық режимдер','Екінші дүниежүзілік соғыс','Отарсыздану үдерісі','Қырғиқабақ соғыс','Араб–израиль қақтығысы','КСРО: жылымық және тоқырау','Қытай реформалары','КСРО-ның ыдырауы және постбиполярлық әлем','Жаһандану','БҰҰ және халықаралық ұйымдар','Қазіргі халықаралық қатынастар','Ғылыми-техникалық революция','Ақпараттық технологиялар','XX–XXI ғасырлар мәдениеті және ЮНЕСКО']}
};

const facts=[
 {date:'Б.з.б. 558 жылдары',event:'Парсылардың патшасы болып ІІ Кир сайланып, Ахеменидтер династиясының негізін қалады.',person:'ІІ Кир'},
 {date:'Б.з.б. 547–546 жылдары',event:'ІІ Кир Армения мен Каппадокияны, Лидияны жаулап алды.',person:'ІІ Кир'},
 {date:'Б.з.б. 538 жылдары',event:'ІІ Кир Вавилон мемлекетін басып алып, оны Парсының құрамына қосты.',person:'ІІ Кир'},
 {date:'Б.з.б. 529 жылы',event:'Каспий даласында массагеттермен болған шайқаста ІІ Кир қаза тапты.',person:'ІІ Кир'},
 {date:'Б.з.б. 526 жылы',event:'Камбиз Египетке қарсы жорыққа аттанды.',person:'Камбиз'},
 {date:'Б.з.б. 525 жылы',event:'Камбиз Египет мемлекетін басып алды.',person:'Камбиз'},
 {date:'Б.з.б. 523 жылы',event:'Камбиз қаза болған соң империяның көптеген аймақтарында көтерілістер болды.',person:'Камбиз'},
 {date:'Б.з.б. 521–486 жылдары',event:'І Дарий билік құрды. Бұл кезең Парсы патшалығының ең өркендеген тұсы болды.',person:'І Дарий'}
];
const persons=[
 {name:'ІІ Кир',clue:'Ахеменидтер династиясының негізін қалады; Мидияны, Лидияны және Вавилонды бағындырды.'},
 {name:'Астиаг',clue:'Мидия патшасы. ІІ Кирден жеңіліп, мемлекеті талқандалды.'},
 {name:'Камбиз',clue:'ІІ Кирдің ұлы. Египетке жорық жасап, оны басып алды.'},
 {name:'І Дарий',clue:'Сатрапилер жүйесін күшейтіп, алым-салық жүйесін реттеп, «Дарик» алтын монетасын шығарды.'},
 {name:'Ариад',clue:'Египеттің сатрапы. Өз бетінше күміс ақша жасай бастағаны үшін І Дарийдің қаһарына ұшырады.'}
];
const tips=['Датаны жеке жаттама — оны оқиға және тұлғамен байланыстырып есте сақта.','Хронологияны жаттағанда алдымен 3 тірек датаны таңда.','Тұлғаны есте сақтау үшін оның бір ерекше ісін тірек ретінде ал.','Күніне 5–10 минуттық қысқа қайталау ұзақ бір реттік оқудан тиімді.'];

const KEY='juzderek_light_v3';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{xp:0,streak:0,lastVisit:null,cardsViewed:[],gamesDone:0,dailyCount:0,dailyDate:null,cardIndex:0,period:'ancient'};
const topicBrowser=document.getElementById('topicBrowser'),studyView=document.getElementById('studyView'),stage=document.getElementById('stage');

function dayKey(d=new Date()){return d.toISOString().slice(0,10)}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function initDay(){const today=dayKey();if(state.dailyDate!==today){state.dailyDate=today;state.dailyCount=0}save()}
function markActivity(){const today=dayKey();if(state.lastVisit!==today){const y=new Date();y.setDate(y.getDate()-1);state.streak=state.lastVisit===dayKey(y)?state.streak+1:1;state.lastVisit=today}}
function addProgress(xp=0,game=false){markActivity();state.xp+=xp;if(game)state.gamesDone++;state.dailyCount=Math.min(10,state.dailyCount+1);save();sync()}
function league(){const levels=[['Бастапқы лига',0,200],['Қола лига',200,500],['Күміс лига',500,900],['Алтын лига',900,1500],['Платина лига',1500,2400],['Гауһар лига',2400,999999]];const x=levels.find(v=>state.xp>=v[1]&&state.xp<v[2])||levels.at(-1);return{name:x[0],min:x[1],max:x[2]}}
function sync(){document.getElementById('topStreak').textContent=(state.streak||0)+' күн';document.getElementById('streakValue').textContent=(state.streak||0)+' күн';document.getElementById('topXp').textContent=state.xp.toLocaleString('kk-KZ')+' XP';document.getElementById('xpValue').textContent=state.xp.toLocaleString('kk-KZ');document.getElementById('cardsViewed').textContent=state.cardsViewed.length;document.getElementById('gamesDone').textContent=state.gamesDone;document.getElementById('goalText').textContent=state.dailyCount+'/10';document.getElementById('goalBar').style.width=(state.dailyCount*10)+'%';const total=facts.length+20,done=state.cardsViewed.length+state.gamesDone,pct=Math.min(100,Math.round(done/total*100));document.getElementById('progressPct').textContent=pct+'%';document.getElementById('progressBar').style.width=pct+'%';const l=league();document.getElementById('leagueName').textContent=l.name;if(l.max>900000){document.getElementById('leagueNext').textContent='Ең жоғары лига';document.getElementById('leagueBar').style.width='100%'}else{document.getElementById('leagueNext').textContent='Келесі лигаға: '+(l.max-state.xp)+' XP';document.getElementById('leagueBar').style.width=Math.max(0,Math.min(100,(state.xp-l.min)/(l.max-l.min)*100))+'%'}const labels=['Дс','Сс','Ср','Бс','Жм','Сн','Жс'],today=(new Date().getDay()+6)%7;document.getElementById('week').innerHTML=labels.map((x,i)=>`<div class="day">${x}<div class="dot ${i<=today&&state.streak>0?'done':''}">${i<=today&&state.streak>0?'✓':''}</div></div>`).join('')}

function renderPeriod(periodKey){state.period=periodKey;save();const p=periodData[periodKey];document.querySelectorAll('.topic').forEach(b=>b.classList.toggle('active',b.dataset.period===periodKey));topicBrowser.innerHTML=`<div class="period-hero"><div><div class="period-icon">${icons[p.icon]}</div><div><div class="period-label">ТАРИХ КЕЗЕҢІ</div><h1>${p.title}</h1><p>${p.description}</p></div></div><div class="period-count">${p.topics.length}<span>тақырып</span></div></div><div class="topic-grid">${p.topics.map((t,i)=>`<button class="topic-card ${t==='Ежелгі Парсы мемлекеті'?'ready':''}" data-title="${t}"><span class="topic-number">${String(i+1).padStart(2,'0')}</span><span class="topic-card-body"><h3>${t}</h3><p>${t==='Ежелгі Парсы мемлекеті'?'Оқуды бастау':'Контент кейін қосылады'}</p></span><span class="topic-arrow">→</span></button>`).join('')}</div>`;studyView.classList.add('hidden');topicBrowser.classList.remove('hidden');topicBrowser.querySelectorAll('.topic-card').forEach(btn=>btn.onclick=()=>{if(btn.dataset.title==='Ежелгі Парсы мемлекеті')openPersia();else{btn.classList.add('pulse');setTimeout(()=>btn.classList.remove('pulse'),400)}})}
function openPersia(){topicBrowser.classList.add('hidden');studyView.classList.remove('hidden');document.querySelector('.study-kicker').textContent='Ежелгі заман';document.getElementById('studyTopicTitle').textContent='Ежелгі Парсы мемлекеті';setGame('cards')}
document.getElementById('backToTopics').onclick=()=>renderPeriod(state.period);document.querySelectorAll('.topic').forEach(b=>b.onclick=()=>renderPeriod(b.dataset.period));

function markCardViewed(i){const id='persia-'+i;if(!state.cardsViewed.includes(id)){state.cardsViewed.push(id);save();sync()}}
function renderCard(){const i=state.cardIndex%facts.length,f=facts[i];markCardViewed(i);stage.innerHTML=`<div class="paper-wrap"><div class="paper-back"></div><div class="binder"></div><article class="paper" id="paperCard"><div class="paper-head"><span>JUZDEREK · Карточка</span><span>${i+1}/${facts.length}</span></div><div class="card-bubble">${i+1}</div><h1 id="cardMain" class="date-front">${f.date}</h1><p id="cardSub">Осы датада қандай оқиға болғанын есіңе түсір. Карточканы аударып, жауабыңды тексер.</p><div class="paper-foot"><span>Алдымен өзің жауап беруге тырыс.</span><div class="paper-actions"><button class="mini-btn" id="prevCard">←</button><button class="mini-btn primary" id="flipCard">Аудару</button><button class="mini-btn" id="nextCard">→</button></div></div></article></div>`;let flipped=false;const flip=()=>{flipped=!flipped;const main=document.getElementById('cardMain'),sub=document.getElementById('cardSub');main.textContent=flipped?f.event:f.date;main.className=flipped?'flip-event':'date-front';sub.textContent=flipped?'Дұрыс жауапты есте сақтап, келесі карточкаға өт.':'Осы датада қандай оқиға болғанын есіңе түсір. Карточканы аударып, жауабыңды тексер.'};document.getElementById('flipCard').onclick=flip;document.getElementById('paperCard').onclick=e=>{if(!e.target.closest('button'))flip()};document.getElementById('nextCard').onclick=()=>{state.cardIndex=(i+1)%facts.length;save();renderCard()};document.getElementById('prevCard').onclick=()=>{state.cardIndex=(i-1+facts.length)%facts.length;save();renderCard()}}

function renderDate(){const q=facts[Math.floor(Math.random()*facts.length)],opts=[q.date,...facts.filter(x=>x.date!==q.date).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.date)].sort(()=>Math.random()-.5);stage.innerHTML=`<div class="quiz-shell"><div class="quiz-title">ДАТАНЫ ТАП</div><div class="quiz-q">${q.event}</div><div class="answers">${opts.map(x=>`<button class="answer">${x}</button>`).join('')}</div><div class="feedback" id="fb"></div></div>`;wireAnswers(q.date,30,renderDate)}
function renderPerson(){const q=persons[Math.floor(Math.random()*persons.length)],opts=[q.name,...persons.filter(x=>x.name!==q.name).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.name)].sort(()=>Math.random()-.5);stage.innerHTML=`<div class="quiz-shell"><div class="quiz-title">ТҰЛҒАНЫ ТАП</div><div class="quiz-q">${q.clue}</div><div class="answers">${opts.map(x=>`<button class="answer">${x}</button>`).join('')}</div><div class="feedback" id="fb"></div></div>`;wireAnswers(q.name,30,renderPerson)}
function wireAnswers(correct,xp,next){let done=false;stage.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{if(done)return;done=true;const ok=b.textContent===correct;b.classList.add(ok?'correct':'wrong');stage.querySelectorAll('.answer').forEach(x=>{if(x.textContent===correct)x.classList.add('correct')});const fb=document.getElementById('fb');fb.style.display='block';fb.innerHTML=ok?'Дұрыс. +'+xp+' XP':'Дұрыс жауап: <b>'+correct+'</b>';addProgress(ok?xp:0,true);const n=document.createElement('button');n.className='mini-btn primary';n.style.marginTop='10px';n.textContent='Келесі →';n.onclick=next;fb.append(document.createElement('br'),n)})}
function yearVal(s){const m=s.match(/(\d{3,4})/);return m?Number(m[1]):0}
function renderChrono(){const chosen=facts.slice(0,5).sort(()=>Math.random()-.5);let order=[];stage.innerHTML=`<div class="chrono-shell"><div class="quiz-title">ХРОНОЛОГИЯ</div><div class="quiz-q">Оқиғаларды реттілігі бойынша орналастырыңыз.</div><div class="chrono-list">${chosen.map((x,i)=>`<button class="chrono-item" data-i="${i}">${x.event}</button>`).join('')}</div><div class="chosen">Таңдалғаны: <span id="chosenText">—</span></div><button class="mini-btn primary" id="checkChrono" style="margin-top:12px">Тексеру</button></div>`;stage.querySelectorAll('.chrono-item').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.i);if(order.includes(i)){order=order.filter(x=>x!==i);b.classList.remove('selected')}else{order.push(i);b.classList.add('selected')}document.getElementById('chosenText').textContent=order.map((x,j)=>(j+1)+'. '+chosen[x].date).join(' → ')||'—'});document.getElementById('checkChrono').onclick=()=>{if(order.length!==chosen.length){alert('Барлық оқиғаны таңдаңыз.');return}const selected=order.map(i=>chosen[i]),correct=[...chosen].sort((a,b)=>yearVal(b.date)-yearVal(a.date)),ok=selected.every((x,i)=>x.date===correct[i].date);document.querySelector('.chosen').innerHTML=ok?'Дұрыс. +50 XP':'Дұрыс рет: <b>'+correct.map(x=>x.date).join(' → ')+'</b>';addProgress(ok?50:0,true)}}
function setGame(name){document.querySelectorAll('.game-tab').forEach(b=>b.classList.toggle('active',b.dataset.game===name));if(name==='cards')renderCard();if(name==='date')renderDate();if(name==='person')renderPerson();if(name==='chrono')renderChrono()}
document.querySelectorAll('.game-tab').forEach(b=>b.onclick=()=>setGame(b.dataset.game));document.getElementById('tipBtn').onclick=()=>document.getElementById('dailyTip').textContent=tips[Math.floor(Math.random()*tips.length)];
initDay();sync();renderPeriod(state.period||'ancient');