const icons={
 temple:'<svg viewBox="0 0 24 24"><path d="M3 10h18M5 10V7l7-4 7 4v3M6 10v8M10 10v8M14 10v8M18 10v8M4 18h16M3 21h18"/></svg>',
 shield:'<svg viewBox="0 0 24 24"><path d="M12 3 5 6v5c0 4.7 2.8 8 7 10 4.2-2 7-5.3 7-10V6l-7-3Z"/></svg>',
 book:'<svg viewBox="0 0 24 24"><path d="M4 5.5A3.5 3.5 0 0 1 7.5 2H20v17H7.5A3.5 3.5 0 0 0 4 22V5.5Z"/><path d="M4 18.5A3.5 3.5 0 0 1 7.5 15H20"/></svg>',
 globe:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/></svg>'
};
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icons[el.dataset.icon]||'');

const periodData={
 ancient:{title:'Ежелгі заман',icon:'temple',description:'Ежелгі өркениеттер мен мемлекеттер.',topics:['Ежелгі Египет','Ежелгі Қосөзен','Ежелгі Қытай','Ежелгі Үндістан','Ежелгі Парсы мемлекеті','Ежелгі Грекия өркениеті','Александр Македонскийдің империясы','Ежелгі Рим өркениеті','Рим империясы','Ежелгі діни нанымдар','Көне философиялық ілімдер','Әлемдік діндер мен өркениеттердің дамуы']},
 medieval:{title:'Орта ғасыр',icon:'shield',description:'Орта ғасырлардағы мемлекеттер мен қоғам.',topics:['Орта ғасырлар түсінігі','Феодалдық қоғам','Ортағасырлық қалалар мен өнер','Халықтардың Ұлы қоныс аударуы және Батыс Рим империясының құлауы','Византия империясы','Киев Русі','Ислам дінінің пайда болуы','Араб халифаты және мұсылман әлемі','Крест жорықтары','Шыңғыс хан','Моңғол империясы','Моңғолдардың әскери өнері','Әмір Темір мемлекеті','Мәскеу мемлекеті','Құбылай мемлекеті және Ильханат','Франция мен Англиядағы шаруалар көтерілісі','Феодалдық соғыстар','Жанна д’Арк','Еуропадағы орталықтанған мемлекеттер','Абсолютизм','Осман империясы','Ұлы Жібек жолы','Ұлы географиялық ашылулар','Реформация','Қайта өрлеу дәуірі','Гуманизм','Шығыстың ортағасырлық мәдениеті']},
 modern:{title:'Жаңа заман',icon:'book',description:'XVII–XIX ғасырлардағы өзгерістер.',topics:['Жаңа заман дәуірі туралы түсінік','Өнеркәсіп төңкерісі және индустриалды қоғам','Ағартушылық дәуірі','XVII ғасырдағы ағылшын революциясы','АҚШ-тың құрылуы және Тәуелсіздік үшін соғыс','Француз революциясы','Наполеон дәуірі','Ресей империясының қалыптасуы','XVII–XVIII ғасырлардағы Үндістан','Еуропалық отаршылдық саясаты','Танзимат реформалары','Қырым соғысы','Апиын соғыстары','1848 жылғы Еуропа революциялары','Германия мен Италияның бірігуі','АҚШ-тағы азамат соғысы','Жапонияның ашылуы','Сипайлар көтерілісі','Үнді Ұлттық Конгресі','XIX ғасырдағы ғылым мен мәдениет']},
 contemporary:{title:'Қазіргі заман',icon:'globe',description:'XX–XXI ғасырлардағы әлем.',topics:['Қазіргі заман ұғымы және оның ерекшеліктері','Бірінші дүниежүзілік соғыс','Версаль–Вашингтон жүйесі','Мұстафа Кемал Ататүрік және Түркия','Махатма Ганди және Үндістан','XX ғасырдағы Қытай','XX ғасырдағы Жапония','1917 жылғы Ресей революциясы','КСРО-ның құрылуы','Ұлы экономикалық дағдарыс','Ф.Д. Рузвельттің Жаңа бағыты','Фашизм және тоталитарлық режимдер','Екінші дүниежүзілік соғыс','Отарсыздану үдерісі','Қырғиқабақ соғыс','Араб–израиль қақтығысы','КСРО: жылымық және тоқырау','Қытай реформалары','КСРО-ның ыдырауы және постбиполярлық әлем','Жаһандану','БҰҰ және халықаралық ұйымдар','Қазіргі халықаралық қатынастар','Ғылыми-техникалық революция','Ақпараттық технологиялар','XX–XXI ғасырлар мәдениеті және ЮНЕСКО']}
};

const facts=[
 {id:'p1',date:'Б.з.б. 558 жылдары',event:'Парсылардың патшасы болып ІІ Кир сайланып, Ахеменидтер династиясының негізін қалады.',person:'ІІ Кир'},
 {id:'p2',date:'Б.з.б. 547–546 жылдары',event:'ІІ Кир Армения мен Каппадокияны, Лидияны жаулап алды.',person:'ІІ Кир'},
 {id:'p3',date:'Б.з.б. 538 жылдары',event:'ІІ Кир Вавилон мемлекетін басып алып, оны Парсының құрамына қосты.',person:'ІІ Кир'},
 {id:'p4',date:'Б.з.б. 529 жылы',event:'Каспий даласында массагеттермен болған шайқаста ІІ Кир қаза тапты.',person:'ІІ Кир'},
 {id:'p5',date:'Б.з.б. 526 жылы',event:'Камбиз Египетке қарсы жорыққа аттанды.',person:'Камбиз'},
 {id:'p6',date:'Б.з.б. 525 жылы',event:'Камбиз Египет мемлекетін басып алды.',person:'Камбиз'},
 {id:'p7',date:'Б.з.б. 523 жылы',event:'Камбиз қаза болған соң империяның көптеген аймақтарында көтерілістер болды.',person:'Камбиз'},
 {id:'p8',date:'Б.з.б. 521–486 жылдары',event:'І Дарий билік құрды. Бұл кезең Парсы патшалығының ең өркендеген тұсы болды.',person:'І Дарий'}
];
const persons=[
 {id:'kir',name:'ІІ Кир',clue:'Ахеменидтер династиясының негізін қалады; Мидияны, Лидияны және Вавилонды бағындырды.'},
 {id:'astiag',name:'Астиаг',clue:'Мидия патшасы. ІІ Кирден жеңіліп, мемлекеті талқандалды.'},
 {id:'kambiz',name:'Камбиз',clue:'ІІ Кирдің ұлы. Египетке жорық жасап, оны басып алды.'},
 {id:'darius',name:'І Дарий',clue:'Сатрапилер жүйесін күшейтіп, алым-салық жүйесін реттеп, «Дарик» алтын монетасын шығарды.'},
 {id:'ariad',name:'Ариад',clue:'Египеттің сатрапы. Өз бетінше күміс ақша жасай бастағаны үшін І Дарийдің қаһарына ұшырады.'}
];
const tips=['Датаны көргенде бірден оқиғаны дауыстап айтып көр.','Қате жауап берген сұрақты кейін қайта орында.','Хронологияда алдымен ең ерте және ең кеш оқиғаны анықта.','Тұлғаны оның бір ерекше әрекетімен байланыстырып есте сақта.'];

const KEY='juzderek_progress_v2';
const defaults={xp:0,streak:0,lastActivity:null,dailyDate:null,dailyCount:0,cardIndex:0,period:'ancient',cardsMastered:[],datesMastered:[],personsMastered:[],chronoMastered:[],correctAnswers:0};
let state={...defaults,...(JSON.parse(localStorage.getItem(KEY)||'null')||{})};
let activeGame='cards';
let session=null;
const topicBrowser=document.getElementById('topicBrowser'),studyView=document.getElementById('studyView'),stage=document.getElementById('stage');

function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function localDay(d=new Date()){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function initDay(){const today=localDay();if(state.dailyDate!==today){state.dailyDate=today;state.dailyCount=0;save()}}
function registerActivity(){const today=localDay();if(state.lastActivity!==today){const yesterday=new Date();yesterday.setDate(yesterday.getDate()-1);state.streak=state.lastActivity===localDay(yesterday)?state.streak+1:1;state.lastActivity=today}state.dailyCount=Math.min(10,state.dailyCount+1);save()}
function award(xp){state.xp+=xp;state.correctAnswers++;registerActivity();save();sync()}
function touchActivity(){registerActivity();save();sync()}
function uniquePush(arr,id){if(arr.includes(id))return false;arr.push(id);return true}
function shuffle(arr){return [...arr].sort(()=>Math.random()-.5)}
function sample(arr,count){return shuffle(arr).slice(0,count)}
function league(){const levels=[['Бастапқы лига',0,200],['Қола лига',200,500],['Күміс лига',500,900],['Алтын лига',900,1500],['Платина лига',1500,2400],['Гауһар лига',2400,999999]];const x=levels.find(v=>state.xp>=v[1]&&state.xp<v[2])||levels.at(-1);return{name:x[0],min:x[1],max:x[2]}}
function topicProgress(){const cards=(state.cardsMastered.length/facts.length)*40;const dates=(state.datesMastered.length/facts.length)*20;const people=(state.personsMastered.length/persons.length)*20;const chrono=(Math.min(state.chronoMastered.length,3)/3)*20;return Math.min(100,Math.round(cards+dates+people+chrono))}
function sync(){
 document.getElementById('topStreak').textContent=(state.streak||0)+' күн';document.getElementById('streakValue').textContent=(state.streak||0)+' күн';
 document.getElementById('topXp').textContent=state.xp.toLocaleString('kk-KZ')+' XP';document.getElementById('xpValue').textContent=state.xp.toLocaleString('kk-KZ');
 document.getElementById('cardsViewed').textContent=state.cardsMastered.length+'/'+facts.length;document.getElementById('gamesDone').textContent=state.correctAnswers;
 document.getElementById('goalText').textContent=state.dailyCount+'/10';document.getElementById('goalBar').style.width=(state.dailyCount*10)+'%';
 const pct=topicProgress();document.getElementById('progressPct').textContent=pct+'%';document.getElementById('progressBar').style.width=pct+'%';
 const l=league();document.getElementById('leagueName').textContent=l.name;
 if(l.max>900000){document.getElementById('leagueNext').textContent='Ең жоғары лига';document.getElementById('leagueBar').style.width='100%'}else{document.getElementById('leagueNext').textContent='Келесі лигаға: '+(l.max-state.xp)+' XP';document.getElementById('leagueBar').style.width=Math.min(100,(state.xp-l.min)/(l.max-l.min)*100)+'%'}
 const labels=['Дс','Сс','Ср','Бс','Жм','Сн','Жс'],today=(new Date().getDay()+6)%7;document.getElementById('week').innerHTML=labels.map((x,i)=>`<div class="day">${x}<div class="dot ${i<=today&&state.streak>0?'done':''}">${i<=today&&state.streak>0?'✓':''}</div></div>`).join('');
}

function renderPeriod(key=state.period){state.period=key;save();const p=periodData[key];document.querySelectorAll('.topic').forEach(b=>b.classList.toggle('active',b.dataset.period===key));topicBrowser.classList.remove('hidden');studyView.classList.add('hidden');topicBrowser.innerHTML=`<div class="period-hero"><div><div class="period-icon">${icons[p.icon]}</div><div><div class="period-label">КЕЗЕҢ</div><h1>${p.title}</h1><p>${p.description}</p></div></div><div class="period-count">${p.topics.length}<span>тақырып</span></div></div><div class="topic-grid">${p.topics.map((t,i)=>{const ready=t==='Ежелгі Парсы мемлекеті';return `<button class="topic-card ${ready?'ready':''}" data-topic="${t}"><span class="topic-number">${String(i+1).padStart(2,'0')}</span><span class="topic-card-body"><h3>${t}</h3><p>${ready?'Оқуды бастау':'Контент кейін қосылады'}</p></span><span class="topic-arrow">→</span></button>`}).join('')}</div>`;topicBrowser.querySelectorAll('.topic-card').forEach(b=>b.onclick=()=>{if(b.dataset.topic==='Ежелгі Парсы мемлекеті')openStudy();else{b.classList.add('pulse');setTimeout(()=>b.classList.remove('pulse'),500)}})}
function openStudy(){topicBrowser.classList.add('hidden');studyView.classList.remove('hidden');document.getElementById('studyTopicTitle').textContent='Ежелгі Парсы мемлекеті';setGame('cards')}
function setGame(name){activeGame=name;session=null;document.querySelectorAll('.game-tab').forEach(b=>b.classList.toggle('active',b.dataset.game===name));if(name==='cards')renderCard();else startSession(name)}

function renderCard(){const i=state.cardIndex%facts.length,f=facts[i];stage.innerHTML=`<div class="paper-wrap"><div class="paper-back"></div><div class="binder"></div><article class="paper" id="paperCard"><div class="paper-head"><span>JUZDEREK · Карточка</span><span>${i+1}/${facts.length}</span></div><div class="card-bubble">${i+1}</div><h1 class="date-front" id="cardMain">${f.date}</h1><p id="cardSub">Датаны көріп, қандай оқиға болғанын еске түсір. Содан кейін карточканы аудар.</p><div class="paper-foot"><span>${state.cardsMastered.includes(f.id)?'Меңгерілді':'Аударғанда +5 XP'}</span><div class="paper-actions"><button class="mini-btn" id="prevCard">←</button><button class="mini-btn primary" id="flipCard">Аудару</button><button class="mini-btn" id="nextCard">→</button></div></div></article></div>`;
 let flipped=false;document.getElementById('flipCard').onclick=()=>flipCard();document.getElementById('paperCard').onclick=e=>{if(!e.target.closest('button'))flipCard()};function flipCard(){flipped=!flipped;document.getElementById('cardMain').textContent=flipped?f.event:f.date;document.getElementById('cardMain').className=flipped?'flip-event':'date-front';document.getElementById('cardSub').textContent=flipped?'Осы оқиғаны датамен бірге есте сақта.':'Датаны көріп, қандай оқиға болғанын еске түсір. Содан кейін карточканы аудар.';if(flipped){touchActivity();if(uniquePush(state.cardsMastered,f.id)){state.xp+=5;save();sync();document.querySelector('.paper-foot>span').textContent='Меңгерілді · +5 XP'}}}
 document.getElementById('nextCard').onclick=()=>{state.cardIndex=(i+1)%facts.length;save();renderCard()};document.getElementById('prevCard').onclick=()=>{state.cardIndex=(i-1+facts.length)%facts.length;save();renderCard()}}

function startSession(game){session={game,total:10,current:0,score:0,answered:false};renderSessionQuestion()}
function sessionHeader(title){const n=session.current+1,pct=Math.round((session.current/session.total)*100);return `<div class="game-progress"><div class="game-progress-top"><span>${title}</span><b>${n}/${session.total}</b></div><div class="track"><span style="width:${pct}%"></span></div></div>`}
function renderSessionQuestion(){if(session.current>=session.total){renderResult();return}if(session.game==='date')renderDateQuestion();if(session.game==='person')renderPersonQuestion();if(session.game==='chrono')renderChronoQuestion()}
function finishQuestion(ok,nextLabel='Келесі сұрақ →'){session.answered=true;if(ok)session.score++;const next=document.createElement('button');next.className='mini-btn primary session-next';next.textContent=nextLabel;next.onclick=()=>{session.current++;session.answered=false;renderSessionQuestion()};return next}
function animateAnswer(el,ok){el.classList.add(ok?'correct':'wrong','answer-pop')}

function renderDateQuestion(){const q=facts[session.current%facts.length],opts=shuffle([q.date,...sample(facts.filter(x=>x.id!==q.id),3).map(x=>x.date)]);stage.innerHTML=`<div class="quiz-shell">${sessionHeader('Датаны тап')}<div class="quiz-title">Оқиғаға сәйкес датаны таңдаңыз</div><div class="quiz-q">${q.event}</div><div class="answers">${opts.map(x=>`<button class="answer">${x}</button>`).join('')}</div><div class="feedback" id="fb"></div></div>`;stage.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{if(session.answered)return;touchActivity();const ok=b.textContent===q.date;animateAnswer(b,ok);stage.querySelectorAll('.answer').forEach(x=>{x.disabled=true;if(x.textContent===q.date)x.classList.add('correct')});const fb=document.getElementById('fb');fb.style.display='block';fb.innerHTML=ok?'<b>Дұрыс!</b> Жақсы, жалғастыра бер.':'<b>Қате.</b> Дұрыс жауап: '+q.date;const first=uniquePush(state.datesMastered,q.id);if(ok&&first)award(15);else{save();sync()}fb.appendChild(finishQuestion(ok))})}

function renderPersonQuestion(){const q=persons[session.current%persons.length],opts=shuffle([q.name,...sample(persons.filter(x=>x.id!==q.id),3).map(x=>x.name)]);stage.innerHTML=`<div class="quiz-shell">${sessionHeader('Тұлғаны тап')}<div class="quiz-title">Сипаттама бойынша тұлғаны таңдаңыз</div><div class="quiz-q">${q.clue}</div><div class="answers">${opts.map(x=>`<button class="answer">${x}</button>`).join('')}</div><div class="feedback" id="fb"></div></div>`;stage.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{if(session.answered)return;touchActivity();const ok=b.textContent===q.name;animateAnswer(b,ok);stage.querySelectorAll('.answer').forEach(x=>{x.disabled=true;if(x.textContent===q.name)x.classList.add('correct')});const fb=document.getElementById('fb');fb.style.display='block';fb.innerHTML=ok?'<b>Дұрыс!</b> Тұлғаны дәл таныдың.':'<b>Қате.</b> Дұрыс жауап: '+q.name;const first=uniquePush(state.personsMastered,q.id);if(ok&&first)award(20);else{save();sync()}fb.appendChild(finishQuestion(ok,'Келесі тұлға →'))})}

function yearValue(s){const m=s.match(/(\d{3,4})/);return m?Number(m[1]):0}
function renderChronoQuestion(){const chosen=sample(facts,4);let order=[];stage.innerHTML=`<div class="chrono-shell">${sessionHeader('Хронология')}<div class="quiz-title">Хронология</div><div class="quiz-q">Оқиғаларды реттілігі бойынша орналастырыңыз.</div><div class="chrono-list">${chosen.map((x,i)=>`<button class="chrono-item" data-i="${i}"><span class="order-num"></span>${x.event}</button>`).join('')}</div><div class="chosen">Оқиғаларды ертеден кешке қарай бір-бірден басыңыз.</div><button class="mini-btn primary" id="checkChrono" style="margin-top:12px">Тексеру</button></div>`;stage.querySelectorAll('.chrono-item').forEach(b=>b.onclick=()=>{if(session.answered)return;const i=Number(b.dataset.i);if(order.includes(i)){order=order.filter(x=>x!==i)}else order.push(i);stage.querySelectorAll('.chrono-item').forEach(x=>{const idx=order.indexOf(Number(x.dataset.i));x.classList.toggle('selected',idx>=0);x.querySelector('.order-num').textContent=idx>=0?idx+1:''})});document.getElementById('checkChrono').onclick=()=>{if(session.answered)return;if(order.length!==chosen.length){document.querySelector('.chosen').textContent='Барлық 4 оқиғаны ретімен таңдаңыз.';return}touchActivity();const selected=order.map(i=>chosen[i]),correct=[...chosen].sort((a,b)=>yearValue(b.date)-yearValue(a.date)),ok=selected.every((x,i)=>x.id===correct[i].id);session.answered=true;if(ok)session.score++;const key=correct.map(x=>x.id).join('-'),first=uniquePush(state.chronoMastered,key);if(ok&&first)award(25);else{save();sync()}document.querySelector('.chrono-list').classList.add(ok?'chrono-correct':'chrono-wrong');const chosenBox=document.querySelector('.chosen');chosenBox.innerHTML=ok?'<b>Дұрыс!</b> Реттілік дұрыс орналастырылды.':'<b>Қате.</b> Дұрыс рет: '+correct.map(x=>x.date).join(' → ');const next=document.createElement('button');next.className='mini-btn primary session-next';next.textContent='Келесі тапсырма →';next.onclick=()=>{session.current++;session.answered=false;renderSessionQuestion()};chosenBox.appendChild(next)} }

function renderResult(){const pct=Math.round((session.score/session.total)*100);let title='Жақсы бастама';if(pct>=90)title='Өте жақсы нәтиже';else if(pct>=70)title='Жақсы нәтиже';else if(pct>=50)title='Тағы бір рет бекітіп ал';const gameNames={date:'Датаны тап',person:'Тұлғаны тап',chrono:'Хронология'};stage.innerHTML=`<div class="result-card"><div class="result-kicker">${gameNames[session.game]} аяқталды</div><div class="result-score">${session.score}<span>/${session.total}</span></div><div class="result-percent">${pct}%</div><h2>${title}</h2><p>${pct>=70?'Тақырыпты жақсы меңгеріп келесің. Қате кеткен сұрақтарды тағы бір рет қайталап шық.':'Қате кеткен деректерді карточка арқылы қайталап, ойынды қайта орындап көр.'}</p><div class="result-track track"><span style="width:${pct}%"></span></div><div class="result-actions"><button class="mini-btn" id="replayGame">Қайта ойнау</button><button class="mini-btn primary" id="nextGame">Келесі ойын →</button></div></div>`;document.getElementById('replayGame').onclick=()=>startSession(session.game);document.getElementById('nextGame').onclick=()=>{const order=['date','person','chrono','cards'];const next=order[(order.indexOf(session.game)+1)%order.length];setGame(next)}}

document.querySelectorAll('.topic').forEach(b=>b.onclick=()=>renderPeriod(b.dataset.period));document.querySelectorAll('.game-tab').forEach(b=>b.onclick=()=>setGame(b.dataset.game));document.getElementById('backToTopics').onclick=()=>renderPeriod(state.period);document.getElementById('tipBtn').onclick=()=>document.getElementById('dailyTip').textContent=tips[Math.floor(Math.random()*tips.length)];
initDay();sync();renderPeriod(state.period);
