const params=new URLSearchParams(location.search);
const requestedTopic=params.get('topic')||'ancient-persia';
const topicRegistry=window.JUZDEREK_TOPICS||{};
const topic=topicRegistry[requestedTopic]||topicRegistry['ancient-persia'];
const facts=topic.facts||[];
const people=topic.people||[];
const TOPIC_ID=topic.id;
const TOPIC_NAME=topic.name;
const MODES=['cards','quiz','person','chrono'];
const MODE_NAMES={cards:'Карточкалар',quiz:'Тест',person:'Тұлғаны тап',chrono:'Хронология'};
let state={mode:'cards',index:0,score:0,total:0,answered:false,sessionXp:0,analysis:{mistakes:0,retries:0,repeatCards:0,repeatItems:[]}};
let chronoOrder=[];
const stage=document.getElementById('stage'),xpEl=document.getElementById('xpValue'),correctEl=document.getElementById('correctValue');
const kicker=document.querySelector('.games-kicker');if(kicker)kicker.textContent=`${topic.period.toUpperCase()} · ${TOPIC_NAME.toUpperCase()}`;
document.title=`JUZDEREK — ${TOPIC_NAME}`;
function safeJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function getProgress(){return safeJSON('juzderek_game_progress',{xp:0,correct:0})}
function getTopicStore(){return safeJSON('juzderek_topics_progress',{})}
function getTopic(){const all=getTopicStore();return all[TOPIC_ID]||{completed:[],scores:{},rewarded:{},topicBonus:false,updatedAt:null}}
function saveTopic(value){const all=getTopicStore();all[TOPIC_ID]=value;localStorage.setItem('juzderek_topics_progress',JSON.stringify(all));renderTopicFlow()}
function touchLearning(){const today=new Date().toISOString().slice(0,10);const meta=safeJSON('juzderek_learning_meta',{lastDay:null,streak:0,bestStreak:0,daily:{}});if(meta.lastDay!==today){const d=new Date();d.setDate(d.getDate()-1);const yesterday=d.toISOString().slice(0,10);meta.streak=meta.lastDay===yesterday?meta.streak+1:1;meta.bestStreak=Math.max(meta.bestStreak,meta.streak);meta.lastDay=today}meta.daily[today]=(meta.daily[today]||0)+1;localStorage.setItem('juzderek_learning_meta',JSON.stringify(meta))}
function saveProgress(addXp=0,addCorrect=0){const p=getProgress();p.xp+=addXp;p.correct+=addCorrect;localStorage.setItem('juzderek_game_progress',JSON.stringify(p));if(addXp||addCorrect)touchLearning();syncScore();window.dispatchEvent(new CustomEvent('juzderek:progress',{detail:p}))}
function rewardOnce(key,xp,correct=1){const t=getTopic();if(t.rewarded[key])return 0;t.rewarded[key]=true;saveTopic(t);saveProgress(xp,correct);state.sessionXp+=xp;return xp}
function completeMode(mode,score,total){const t=getTopic();const pct=total?Math.round(score/total*100):100;t.scores[mode]={score,total,pct,finishedAt:Date.now(),analysis:{...state.analysis}};let bonus=0;if(pct===100&&!t.completed.includes(mode)){t.completed.push(mode);bonus+=50}if(t.completed.length===MODES.length&&!t.topicBonus){t.topicBonus=true;bonus+=100}t.updatedAt=Date.now();saveTopic(t);if(bonus){saveProgress(bonus,0);state.sessionXp+=bonus}return bonus}
function syncScore(){const p=getProgress();xpEl.textContent=p.xp+' XP';correctEl.textContent=p.correct+' дұрыс'}
function progressPct(i,total){return Math.round((i/total)*100)}
function renderTopicFlow(){const old=document.querySelector('.topic-flow');if(old)old.remove();const t=getTopic(),done=t.completed.length,pct=Math.round(done/MODES.length*100);const el=document.createElement('section');el.className='topic-flow';el.innerHTML=`<div class="topic-flow-main"><div class="topic-flow-top"><span class="topic-flow-title">${TOPIC_NAME}</span><span class="topic-flow-meta">${done}/4 бөлім аяқталды · ${pct}%</span></div><div class="topic-flow-track"><span style="width:${pct}%"></span></div></div><div class="topic-flow-steps">${MODES.map(m=>`<span class="topic-flow-step ${t.completed.includes(m)?'done':state.mode===m?'current':''}"><i></i>${MODE_NAMES[m]}</span>`).join('')}</div>`;document.querySelector('.game-tabs').after(el)}
function setMode(mode){state={mode,index:0,score:0,total:0,answered:false,sessionXp:0,analysis:{mistakes:0,retries:0,repeatCards:0,repeatItems:[]}};chronoOrder=[];document.querySelectorAll('.game-tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));renderTopicFlow();render()}
window.setMode=setMode;
document.querySelectorAll('.game-tab').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
function render(){if(state.mode==='cards')renderCards();if(state.mode==='quiz')renderQuiz();if(state.mode==='person')renderPerson();if(state.mode==='chrono')renderChrono()}
function renderCards(){const f=facts[state.index];if(!f){completeMode('cards',state.score,facts.length);showResult('Карточкалар аяқталды!',state.score,facts.length);return}stage.innerHTML=`<div class="stage-top"><div class="stage-title"><h2>Карточкалар</h2><p>Датаны оқы. Қандай оқиға болғанын есіңе түсіріп, карточканы аудар.</p></div><span class="step-counter">${state.index+1} / ${facts.length}</span></div><div class="progress-line"><span style="width:${progressPct(state.index,facts.length)}%"></span></div><div class="flash-wrap"><div class="flashcard" id="flashcard" role="button" tabindex="0"><div class="flash-face flash-front"><span class="flash-label">ДАТА</span><div class="flash-date">${f.date}</div><div class="flash-divider"></div><div class="tap-hint">Қандай оқиға болғанын ойла да, карточканы аудар</div></div><div class="flash-face flash-back"><span class="flash-label">ОҚИҒА</span><div class="flash-event">${f.event}</div><div class="flash-divider"></div><div class="tap-hint">Жауабыңды тексердің бе? Келесі карточкаға өт</div></div></div></div><div class="card-actions"><button class="btn soft" id="repeatBtn">Қайталау керек</button><button class="btn primary" id="knowBtn">Білемін</button></div>`;const card=document.getElementById('flashcard');const flip=()=>card.classList.toggle('flipped');card.onclick=flip;card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip()}});document.getElementById('repeatBtn').onclick=()=>{state.analysis.repeatCards++;state.analysis.mistakes++;if(!state.analysis.repeatItems.some(x=>x.id===f.id))state.analysis.repeatItems.push({id:f.id,date:f.date,event:f.event});state.index++;renderCards()};document.getElementById('knowBtn').onclick=()=>{state.score++;rewardOnce(`cards:${f.id}`,10,1);state.index++;renderCards()}}
function quizOptions(correct){const others=facts.filter(x=>x.event!==correct).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.event);return [...others,correct].sort(()=>Math.random()-.5)}
function renderQuiz(){const f=facts[state.index];if(!f){completeMode('quiz',state.score,facts.length);showResult('Тест аяқталды!',state.score,facts.length);return}const opts=quizOptions(f.event);stage.innerHTML=`<div class="stage-top"><div class="stage-title"><h2>Тест</h2><p>Берілген датаға сәйкес оқиғаны таңда.</p></div><span class="step-counter">${state.index+1} / ${facts.length}</span></div><div class="progress-line"><span style="width:${progressPct(state.index,facts.length)}%"></span></div><div class="question-card"><span class="flash-label date-accent">${f.date}</span><h3>Осы датада қандай оқиға болды?</h3><div class="answers">${opts.map(o=>`<button class="answer" data-answer="${encodeURIComponent(o)}">${o}</button>`).join('')}</div><div class="feedback" id="feedback"></div></div>`;document.querySelectorAll('.answer').forEach(btn=>btn.onclick=()=>{if(state.answered)return;state.answered=true;const ans=decodeURIComponent(btn.dataset.answer),ok=ans===f.event;btn.classList.add(ok?'correct':'wrong');if(!ok){state.analysis.mistakes++;[...document.querySelectorAll('.answer')].find(b=>decodeURIComponent(b.dataset.answer)===f.event)?.classList.add('correct')}const fb=document.getElementById('feedback');fb.classList.add('show');const earned=ok?rewardOnce(`quiz:${f.id}`,20,1):0;fb.textContent=ok?`Дұрыс!${earned?` +${earned} XP`:''}`:'Дұрыс жауап: '+f.event;if(ok)state.score++;setTimeout(()=>{state.index++;state.answered=false;renderQuiz()},1200)})}
function personOptions(correct){const others=people.filter(x=>x.name!==correct).map(x=>x.name).sort(()=>Math.random()-.5).slice(0,3);return [...others,correct].sort(()=>Math.random()-.5)}
function renderPerson(){const p=people[state.index];if(!p){completeMode('person',state.score,people.length);showResult('Тұлғаны тап аяқталды!',state.score,people.length);return}const opts=personOptions(p.name);const clue=(p.clue||'').replace(/\n/g,'<br>');stage.innerHTML=`<div class="stage-top"><div class="stage-title"><h2>Тұлғаны тап</h2><p>Сипаттамаға қарап, дұрыс тарихи тұлғаны таңда.</p></div><span class="step-counter">${state.index+1} / ${people.length}</span></div><div class="progress-line"><span style="width:${progressPct(state.index,people.length)}%"></span></div><div class="person-question"><div class="person-hero-card"><div class="person-visual"><img src="./assets/person.webp" alt="Тарихи тұлға"></div><div class="person-copy"><span class="person-badge">БҰЛ КІМ?</span><h3>Тарихи тұлғаны анықта</h3><div class="person-clue">${clue}</div></div></div><div class="answers person-answers">${opts.map((o,i)=>`<button class="answer person-answer" data-person="${encodeURIComponent(o)}"><span class="option-letter">${String.fromCharCode(65+i)}</span><span>${o}</span></button>`).join('')}</div><div class="feedback" id="personFeedback"></div></div>`;document.querySelectorAll('.person-answer').forEach(btn=>btn.onclick=()=>{if(state.answered)return;state.answered=true;const ans=decodeURIComponent(btn.dataset.person),ok=ans===p.name;btn.classList.add(ok?'correct':'wrong');if(!ok){state.analysis.mistakes++;[...document.querySelectorAll('.person-answer')].find(b=>decodeURIComponent(b.dataset.person)===p.name)?.classList.add('correct')}const fb=document.getElementById('personFeedback');fb.classList.add('show');const earned=ok?rewardOnce(`person:${p.id}`,25,1):0;fb.textContent=ok?`Дұрыс! ${p.name}${earned?` · +${earned} XP`:''}`:'Дұрыс жауап: '+p.name;if(ok)state.score++;setTimeout(()=>{state.index++;state.answered=false;renderPerson()},1200)})}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function renderChrono(){if(typeof window.renderChrono==='function'&&window.renderChrono!==renderChrono)return window.renderChrono();}
syncScore();renderTopicFlow();render();