const facts=[
{date:'Б.з.б. 558 жылдары',event:'Парсылардың патшасы болып ІІ Кир сайланып, Ахеменидтер династиясының негізін қалады.',person:'ІІ Кир'},
{date:'Б.з.б. 547–546 жылдары',event:'ІІ Кир Армения мен Каппадокияны, Лидияны жаулап алды.',person:'ІІ Кир'},
{date:'Б.з.б. 538 жылдары',event:'ІІ Кир Вавилон мемлекетін басып алып, оны Парсының құрамына қосты.',person:'ІІ Кир'},
{date:'Б.з.б. 529 жылы',event:'Каспий даласында массагеттермен болған шайқаста ІІ Кир қаза тапты.',person:'ІІ Кир'},
{date:'Б.з.б. 526 жылы',event:'Камбиз Египетке қарсы жорыққа аттанды.',person:'Камбиз'},
{date:'Б.з.б. 525 жылы',event:'Камбиз Египет мемлекетін басып алды.',person:'Камбиз'},
{date:'Б.з.б. 523 жылы',event:'Камбиз қаза болған соң империяның көптеген аймақтарында көтерілістер болды.',person:'Камбиз'},
{date:'Б.з.б. 521–486 жылдары',event:'І Дарий билік құрды. Бұл кезең Парсы патшалығының ең өркендеген тұсы болды.',person:'І Дарий'}
];
const people=[
{name:'ІІ Кир',clue:'Ахеменидтер династиясының негізін қалады; Мидияны, Лидияны және Вавилонды бағындырды.'},
{name:'Камбиз',clue:'ІІ Кирдің ұлы. Египетке жорық жасап, оны басып алды.'},
{name:'І Дарий',clue:'Парсы мемлекетін сатрапилерге бөліп, салық жүйесін реттеп, империяны күшейтті.'},
{name:'Астиаг',clue:'Мидия патшасы. ІІ Кирден жеңіліп, оның мемлекеті Парсы билігіне өтті.'}
];
let state={mode:'cards',index:0,score:0,total:0,answered:false};
const stage=document.getElementById('stage');
const xpEl=document.getElementById('xpValue');
const correctEl=document.getElementById('correctValue');
function getProgress(){return JSON.parse(localStorage.getItem('juzderek_game_progress')||'{"xp":0,"correct":0}')}function saveProgress(addXp=0,addCorrect=0){const p=getProgress();p.xp+=addXp;p.correct+=addCorrect;localStorage.setItem('juzderek_game_progress',JSON.stringify(p));syncScore()}function syncScore(){const p=getProgress();xpEl.textContent=p.xp+' XP';correctEl.textContent=p.correct+' дұрыс'}syncScore();
function progressPct(i,total){return Math.round((i/total)*100)}
function setMode(mode){state={mode,index:0,score:0,total:0,answered:false};document.querySelectorAll('.game-tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));render()}
document.querySelectorAll('.game-tab').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
function render(){if(state.mode==='cards')renderCards();if(state.mode==='quiz')renderQuiz();if(state.mode==='person')renderPerson();if(state.mode==='chrono')renderChrono()}
function renderCards(){const f=facts[state.index];if(!f){showResult('Карточкалар аяқталды!',facts.length,0);return}stage.innerHTML=`<div class="stage-top"><div class="stage-title"><h2>Карточкалар</h2><p>Оқиғаны оқы. Қай жылы болғанын есіңе түсіріп, карточканы аудар.</p></div><span class="step-counter">${state.index+1} / ${facts.length}</span></div><div class="progress-line"><span style="width:${progressPct(state.index,facts.length)}%"></span></div><div class="flash-wrap"><div class="flashcard" id="flashcard" role="button" tabindex="0" aria-label="Карточканы аудару"><div class="flash-face flash-front"><span class="flash-label">ОҚИҒА</span><div class="flash-event">${f.event}</div><div class="flash-divider"></div><div class="tap-hint">Қай жылы болғанын ойла да, карточканы аудар</div></div><div class="flash-face flash-back"><span class="flash-label">ДАТА</span><div class="flash-date">${f.date}</div><div class="flash-divider"></div><div class="tap-hint">Жауабыңды тексердің бе? Келесі карточкаға өт</div></div></div></div><div class="card-actions"><button class="btn soft" id="repeatBtn">Қайталау керек</button><button class="btn primary" id="knowBtn">Білемін</button></div>`;const card=document.getElementById('flashcard');const flip=()=>card.classList.toggle('flipped');card.onclick=flip;card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip()}});document.getElementById('repeatBtn').onclick=()=>{state.index++;renderCards()};document.getElementById('knowBtn').onclick=()=>{saveProgress(10,1);state.index++;renderCards()}}
function quizOptions(correct){const others=facts.filter(x=>x.event!==correct).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.event);return [...others,correct].sort(()=>Math.random()-.5)}
function renderQuiz(){const f=facts[state.index];if(!f){showResult('Тест аяқталды!',state.score,facts.length);return}const opts=quizOptions(f.event);stage.innerHTML=`<div class="stage-top"><div class="stage-title"><h2>Тест</h2><p>Берілген датаға сәйкес оқиғаны таңда.</p></div><span class="step-counter">${state.index+1} / ${facts.length}</span></div><div class="progress-line"><span style="width:${progressPct(state.index,facts.length)}%"></span></div><div class="question-card"><span class="flash-label date-accent">${f.date}</span><h3>Осы датада қандай оқиға болды?</h3><div class="answers">${opts.map(o=>`<button class="answer" data-answer="${encodeURIComponent(o)}">${o}</button>`).join('')}</div><div class="feedback" id="feedback"></div></div>`;document.querySelectorAll('.answer').forEach(btn=>btn.onclick=()=>{if(state.answered)return;state.answered=true;const ans=decodeURIComponent(btn.dataset.answer);const ok=ans===f.event;btn.classList.add(ok?'correct':'wrong');if(!ok)[...document.querySelectorAll('.answer')].find(b=>decodeURIComponent(b.dataset.answer)===f.event)?.classList.add('correct');const fb=document.getElementById('feedback');fb.classList.add('show');fb.textContent=ok?'Дұрыс! +20 XP':'Дұрыс жауап: '+f.event;if(ok){state.score++;saveProgress(20,1)}setTimeout(()=>{state.index++;state.answered=false;renderQuiz()},1200)})}
function personOptions(correct){const others=people.filter(x=>x.name!==correct).map(x=>x.name).sort(()=>Math.random()-.5).slice(0,3);return [...others,correct].sort(()=>Math.random()-.5)}
function renderPerson(){const p=people[state.index];if(!p){showResult('Тұлғаны тап аяқталды!',state.score,people.length);return}const opts=personOptions(p.name);stage.innerHTML=`<div class="stage-top"><div class="stage-title"><h2>Тұлғаны тап</h2><p>Сипаттамаға қарап, дұрыс тарихи тұлғаны таңда.</p></div><span class="step-counter">${state.index+1} / ${people.length}</span></div><div class="progress-line"><span style="width:${progressPct(state.index,people.length)}%"></span></div><div class="person-question"><div class="person-hero-card"><div class="person-visual"><img src="./assets/person.webp" alt="Тарихи тұлға"></div><div class="person-copy"><span class="person-badge">БҰЛ КІМ?</span><h3>Тарихи тұлғаны анықта</h3><div class="person-clue">${p.clue}</div></div></div><div class="answers person-answers">${opts.map((o,i)=>`<button class="answer person-answer" data-person="${encodeURIComponent(o)}"><span class="option-letter">${String.fromCharCode(65+i)}</span><span>${o}</span></button>`).join('')}</div><div class="feedback" id="personFeedback"></div></div>`;document.querySelectorAll('.person-answer').forEach(btn=>btn.onclick=()=>{if(state.answered)return;state.answered=true;const ans=decodeURIComponent(btn.dataset.person);const ok=ans===p.name;btn.classList.add(ok?'correct':'wrong');if(!ok)[...document.querySelectorAll('.person-answer')].find(b=>decodeURIComponent(b.dataset.person)===p.name)?.classList.add('correct');const fb=document.getElementById('personFeedback');fb.classList.add('show');fb.textContent=ok?'Дұрыс! '+p.name+' · +25 XP':'Дұрыс жауап: '+p.name;if(ok){state.score++;saveProgress(25,1)}setTimeout(()=>{state.index++;state.answered=false;renderPerson()},1200)})}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
let chronoOrder=[];function renderChrono(){if(!chronoOrder.length)chronoOrder=shuffle(facts.slice(0,5));stage.innerHTML=`<div class="stage-top"><div class="stage-title"><h2>Хронология</h2><p>Оқиғаларды реттілігі бойынша орналастырыңыз.</p></div><span class="step-counter">5 оқиға</span></div><div class="progress-line"><span style="width:0%"></span></div><div class="chrono-list" id="chronoList">${chronoOrder.map((f,i)=>`<div class="chrono-item" draggable="true" data-date="${f.date}"><span class="drag-num">${i+1}</span><span>${f.event}</span><span class="drag-handle">⋮⋮</span></div>`).join('')}</div><div class="chrono-actions"><button class="btn primary" id="checkChrono">Реттілікті тексеру</button></div><div class="feedback" id="chronoFeedback" style="max-width:900px;margin:18px auto 0"></div>`;let drag=null;document.querySelectorAll('.chrono-item').forEach(item=>{item.addEventListener('dragstart',()=>{drag=item;item.classList.add('dragging')});item.addEventListener('dragend',()=>{item.classList.remove('dragging');drag=null;refreshNums()});item.addEventListener('dragover',e=>{e.preventDefault();const list=document.getElementById('chronoList');const target=e.currentTarget;if(drag&&target!==drag){const r=target.getBoundingClientRect();list.insertBefore(drag,e.clientY<r.top+r.height/2?target:target.nextSibling)}})});document.getElementById('checkChrono').onclick=()=>{const dates=[...document.querySelectorAll('.chrono-item')].map(x=>x.dataset.date);const correct=facts.slice(0,5).map(x=>x.date);const ok=dates.every((d,i)=>d===correct[i]);const fb=document.getElementById('chronoFeedback');fb.classList.add('show');fb.textContent=ok?'Керемет! Реттілік дұрыс. +50 XP':'Әзірге дұрыс емес. Қайта орналастырып көр.';if(ok){saveProgress(50,1);document.getElementById('checkChrono').disabled=true}}}
function refreshNums(){document.querySelectorAll('.chrono-item .drag-num').forEach((n,i)=>n.textContent=i+1)}
function showResult(title,score,total){stage.innerHTML=`<div class="result-card"><div class="result-icon">✓</div><h2>${title}</h2><p>Жақсы жұмыс! Прогрессің автоматты түрде сақталды.</p>${total?`<div class="result-stats"><div><b>${score}/${total}</b><span>дұрыс жауап</span></div><div><b>${Math.round(score/total*100)}%</b><span>нәтиже</span></div></div>`:''}<button class="btn primary" onclick="setMode('${state.mode}')">Қайта бастау</button></div>`}
const params=new URLSearchParams(location.search);const initial=params.get('mode');if(['cards','quiz','person','chrono'].includes(initial))setMode(initial);else render();
