(()=>{
  const demo=[
    ['Айбар',2840,'Тарихшы'],['Аружан',2610,'Тарихшы'],['Нұрасыл',2430,'Сарапшы'],['Диас',2210,'Сарапшы'],['Айша',2050,'Сарапшы'],['Медина',1980,'Білгір'],['Нұрбек',1840,'Білгір'],['Алина',1760,'Білгір'],['Әлихан',1680,'Білгір'],['Кәусар',1590,'Білгір'],['Дамир',1490,'Зерттеуші'],['Мерей',1410,'Зерттеуші'],['Санжар',1320,'Зерттеуші'],['Жансая',1240,'Зерттеуші'],['Рауан',1160,'Ізденуші']
  ];
  function getUser(){let p={xp:0};try{p=JSON.parse(localStorage.getItem('juzderek_game_progress')||'{"xp":0}')}catch{}return{name:localStorage.getItem('juzderek_username')||'Сен',xp:Number(p.xp)||0,rank:(()=>{const x=Number(p.xp)||0;if(x>=38000)return'Аңыз';if(x>=20000)return'Тарихшы';if(x>=9500)return'Сарапшы';if(x>=3500)return'Білгір';if(x>=1200)return'Зерттеуші';return'Ізденуші'})()}}
  function rows(){const u=getUser();const all=demo.map(x=>({name:x[0],xp:x[1],rank:x[2],me:false}));all.push({...u,me:true});all.sort((a,b)=>b.xp-a.xp);return all}
  function open(){if(document.querySelector('.full-leaderboard-overlay'))return;const data=rows(),meIndex=data.findIndex(x=>x.me);const top=data.slice(0,15);const modal=document.createElement('div');modal.className='full-leaderboard-overlay';modal.innerHTML=`<div class="full-leaderboard-modal" role="dialog" aria-modal="true" aria-label="Үздіктер тақтасы"><div class="fl-head"><div><span class="fl-kicker">ОСЫ АПТА</span><h2>Үздіктер тақтасы</h2><p>XP бойынша үздік оқушылар рейтингі</p></div><button class="fl-close" type="button" aria-label="Жабу">×</button></div><div class="fl-podium">${top.slice(0,3).map((r,i)=>`<div class="fl-podium-card p${i+1}"><span class="fl-medal">${['🥇','🥈','🥉'][i]}</span><strong>${r.name}</strong><small>${r.rank}</small><b>${r.xp.toLocaleString('kk-KZ')} XP</b></div>`).join('')}</div><div class="fl-table-head"><span>Орын</span><span>Оқушы</span><span>Атақ</span><span>XP</span></div><div class="fl-list">${top.map((r,i)=>`<div class="fl-row${r.me?' me':''}"><span class="fl-place">${i+1}</span><span class="fl-name">${r.name}${r.me?'<em>СЕН</em>':''}</span><span class="fl-rank">${r.rank}</span><b>${r.xp.toLocaleString('kk-KZ')} XP</b></div>`).join('')}</div>${meIndex>14?`<div class="fl-my-position"><span>Сенің орның</span><strong>#${meIndex+1}</strong><b>${data[meIndex].xp.toLocaleString('kk-KZ')} XP</b></div>`:''}<div class="fl-note">Рейтинг қазір демо режимінде. Сенің XP-ың браузерде сақталады.</div></div>`;document.body.appendChild(modal);document.body.classList.add('leaderboard-open');const close=()=>{modal.remove();document.body.classList.remove('leaderboard-open')};modal.querySelector('.fl-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.addEventListener('keydown',function esc(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',esc)}})}
  function bind(){document.querySelectorAll('.leaderboard-card .text-btn,.profile-menu-link').forEach(el=>{if(/Толық рейтинг|Үздіктер тақтасы/i.test(el.textContent||'')){el.onclick=e=>{e.preventDefault();e.stopPropagation();open()}}});document.querySelectorAll('.site-nav-link').forEach(el=>{if(/Үздіктер/i.test(el.textContent||'')){el.onclick=e=>{e.preventDefault();open()}}})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();new MutationObserver(bind).observe(document.documentElement,{childList:true,subtree:true});window.openJuzLeaderboard=open;
})();