(()=>{
  const RANK_IMAGES={'Ізденуші':'./assets/level-seeker.webp','Зерттеуші':'./assets/level-researcher.webp','Білгір':'./assets/level-scholar.webp','Сарапшы':'./assets/level-expert.webp','Тарихшы':'./assets/level-historian.webp','Аңыз':'./assets/level-legend.webp'};
  const safeJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
  const currentXp=()=>Math.max(0,Number(safeJSON('juzderek_game_progress',{xp:0}).xp)||0);
  const levels=()=>window.JUZ_PROGRESS_CORE?.LEVELS||window.JUZ_LEVELS||[{level:1,name:'Ізденуші',min:0}];
  function levelInfo(xp){const ls=levels();let current=ls[0];for(const item of ls){if(xp>=item.min)current=item;else break}const idx=ls.findIndex(x=>x.level===current.level),next=ls[idx+1]||null;const pct=next?clamp(Math.round((xp-current.min)/(next.min-current.min)*100),0,100):100;return{...current,next,pct,need:next?Math.max(0,next.min-xp):0}}
  function rankSteps(){const seen=new Set(),out=[];for(const l of levels()){if(!seen.has(l.name)){seen.add(l.name);out.push({name:l.name,min:l.min,image:RANK_IMAGES[l.name]})}}return out}
  function rankInfo(xp){const ranks=rankSteps();let current=ranks[0];for(const r of ranks){if(xp>=r.min)current=r;else break}const index=ranks.indexOf(current);return{current,index,next:ranks[index+1]||null,ranks}}
  function journeyHTML(rank){return rank.ranks.map((r,index)=>{const state=index<rank.index?'done':index===rank.index?'current':'locked';return `<div class="level-journey-step ${state}" data-rank-index="${index}"><div class="level-character-wrap"><img class="level-character" src="${r.image}" alt="${r.name}" loading="lazy"></div><div class="level-journey-dot"><span>${index<rank.index?'✓':index+1}</span></div><div class="level-journey-step-copy"><strong>${r.name}</strong><small>${r.min.toLocaleString('kk-KZ')} XP</small></div></div>`}).join('')}
  function centerActiveStep(host,activeIndex){if(!window.matchMedia('(max-width:640px)').matches)return;requestAnimationFrame(()=>{const route=host.querySelector('.level-journey-route'),active=route?.querySelector(`[data-rank-index="${activeIndex}"]`);if(route&&active){const left=active.offsetLeft-(route.clientWidth-active.offsetWidth)/2;route.scrollTo({left:Math.max(0,left),behavior:'auto'})}})}
  function render(){const recentCard=document.querySelector('.recent-card');if(!recentCard)return;const xp=currentXp(),level=levelInfo(xp),rank=rankInfo(xp);let host=recentCard.querySelector('#levelJourney');if(!host){host=document.createElement('section');host.id='levelJourney';host.className='level-journey';recentCard.appendChild(host)}const nextLevelText=level.next?`Келесі level-ге ${level.need.toLocaleString('kk-KZ')} XP қалды`:'Ең жоғары level';const rankTarget=rank.next?.min||xp,rankBase=rank.current.min,rankPct=rank.next?clamp(Math.round((xp-rankBase)/(rankTarget-rankBase)*100),0,100):100;host.innerHTML=`<div class="level-desktop-summary"><div class="level-journey-head"><div><span class="level-journey-kicker">СЕНІҢ ДЕҢГЕЙІҢ</span><div class="level-journey-title-row"><h3>${rank.current.name}</h3><span class="level-chip">Lv.${level.level}</span></div><p>${nextLevelText}</p></div><div class="level-xp-total"><strong>${xp.toLocaleString('kk-KZ')} XP</strong><span>${rank.next?`Келесі атақ: ${rank.next.name}`:'Максималды атақ'}</span></div></div><div class="level-progress-wrap"><div class="level-progress-meta"><span>${level.min.toLocaleString('kk-KZ')} XP</span><strong>${level.pct}%</strong><span>${(level.next?.min||xp).toLocaleString('kk-KZ')} XP</span></div><div class="level-progress-track"><span style="width:${level.pct}%"></span></div></div></div><div class="level-mobile-summary"><div class="level-mobile-current"><img src="${RANK_IMAGES[rank.current.name]}" alt="${rank.current.name}" class="level-mobile-character"><div class="level-mobile-copy"><div class="level-mobile-title"><strong>${rank.current.name}</strong><span class="level-chip">Lv.${level.level}</span></div><b>${xp.toLocaleString('kk-KZ')} / ${rankTarget.toLocaleString('kk-KZ')} XP</b><div class="level-mobile-track"><span style="width:${rankPct}%"></span></div><small>${rank.next?`${rank.next.name}ге ${Math.max(0,rank.next.min-xp).toLocaleString('kk-KZ')} XP қалды`:'Ең жоғары атаққа жеттің!'}</small></div></div></div><div class="level-journey-route" aria-label="Атақтар жолы">${journeyHTML(rank)}</div><div class="level-mobile-hint">← Сырғытып, барлық деңгейлерді көр →</div>`;centerActiveStep(host,rank.index)}
  const schedule=()=>requestAnimationFrame(render);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule);else schedule();window.addEventListener('juzderek:progress',schedule);window.addEventListener('storage',e=>{if(e.key==='juzderek_game_progress')schedule()});window.addEventListener('pageshow',schedule);window.addEventListener('resize',()=>{const host=document.querySelector('#levelJourney');if(host)centerActiveStep(host,rankInfo(currentXp()).index)});
})();