(()=>{
  if(window.__JUZ_ONBOARDING)return;window.__JUZ_ONBOARDING=true;
  const KEY='juzderek_onboarding_v1';
  const CSS='./onboarding.css?v=20260824-01';
  const steps=[
    {kicker:'Қош келдің!',title:'JUZDEREK-пен <span>танысайық</span>',text:'Бұл жерде тарихты жай оқымайсың: тақырыптарды меңгеріп, ойын ойнап, прогресіңді көріп, жетістіктер жинайсың.',visual:`<div class="onboard-visual-card"><img class="onboard-mascot" src="./assets/mascot-progress.webp" alt="JUZDEREK маскоты"></div>`},
    {kicker:'1 · Тақырыптар',title:'Бүкіл тарих <span>ретімен</span>',text:'Кезеңді таңдап, сол дәуірдің тақырыптарын ашасың. Әр тақырып бір жүйемен берілген, сондықтан қай жерде қалғаныңды жоғалтпайсың.',visual:`<div class="onboard-visual-card"><div class="onboard-feature-grid"><div class="onboard-feature"><img src="./assets/ancient.webp" alt=""><div><strong>Ежелгі заман</strong><small>Тақырыптарды баста</small></div></div><div class="onboard-feature"><img src="./assets/medieval.webp" alt=""><div><strong>Орта ғасыр</strong><small>Кезеңмен жалғастыр</small></div></div><div class="onboard-feature onboard-wide"><img src="./assets/modern.webp" alt=""><div><strong>Барлығы бір жүйеде</strong><small>Кезең → тақырып → ойындар</small></div></div></div></div>`},
    {kicker:'2 · Ойындар',title:'Оқығаныңды <span>бекіт</span>',text:'Карточка, тест, хронология және кейіпкерді тану арқылы тақырыпты бірнеше қырынан қайталайсың.',visual:`<div class="onboard-visual-card"><div class="onboard-feature-grid"><div class="onboard-feature"><img src="./assets/cards.webp" alt=""><div><strong>Карточкалар</strong><small>Дата ↔ оқиға</small></div></div><div class="onboard-feature"><img src="./assets/test.webp" alt=""><div><strong>Тест</strong><small>Біліміңді тексер</small></div></div><div class="onboard-feature"><img src="./assets/chronology.webp" alt=""><div><strong>Хронология</strong><small>Реттілікті тап</small></div></div><div class="onboard-feature"><img src="./assets/person.webp" alt=""><div><strong>Кейіпкерді таны</strong><small>Тұлғаны анықта</small></div></div></div></div>`},
    {kicker:'3 · Прогресс',title:'Өсуіңді <span>көріп отыр</span>',text:'XP, streak және меңгерілген тақырыптар автоматты түрде есептеледі. Трекер қай тақырыптарды бекіткеніңді көрсетеді.',visual:`<div class="onboard-visual-card"><div class="onboard-stat-row"><div class="onboard-stat"><img src="./assets/xp.webp" alt=""><b>XP</b><span>Әр әрекетке ұпай</span></div><div class="onboard-stat"><img src="./assets/streak.webp" alt=""><b>Streak</b><span>Күндік тұрақтылық</span></div><div class="onboard-stat"><img src="./assets/target.webp" alt=""><b>Трекер</b><span>Тақырып прогресі</span></div></div></div>`},
    {kicker:'4 · Жетістіктер',title:'Оқыған сайын <span>ашыла береді</span>',text:'Жетістіктер мен коллекция сенің еңбегіңді визуалды түрде көрсетеді. Тақырып меңгерген сайын жаңа белгілер мен карточкалар жиналады.',visual:`<div class="onboard-visual-card"><div class="onboard-achieve"><div><img src="./assets/achievement-juzderek-legend.webp" alt=""><b>Жетістіктер</b></div><div><img src="./assets/chest-open.webp" alt=""><b>Коллекция</b></div></div></div>`},
    {kicker:'5 · Кері байланыс',title:'Сұрағың болса — <span>жаз</span>',text:'Кез келген беттен маскотты басып, сұрақ немесе ұсыныс жібере аласың. Жауап келгенде маскот саған белгі береді.',visual:`<div class="onboard-visual-card"><div class="onboard-support-preview"><img src="./assets/mascot-progress.webp" alt=""><div class="onboard-chat-bubble"><strong>Сұрағыңыз бар ма?</strong>Маскотты бас → сұрағыңды жаз → жауапты осы жерден көр.</div></div></div>`}
  ];
  const q=(s,r=document)=>r.querySelector(s);
  function ensureCss(){if(q('link[data-juz-onboarding]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=CSS;l.dataset.juzOnboarding='1';document.head.appendChild(l)}
  let idx=0,root=null;
  function render(){if(!root)return;const s=steps[idx];q('.onboard-count',root).textContent=`${idx+1} / ${steps.length}`;q('.onboard-progress span',root).style.width=`${((idx+1)/steps.length)*100}%`;q('.onboard-body',root).innerHTML=`<div class="onboard-copy onboard-step"><div class="onboard-kicker">${s.kicker}</div><h2>${s.title}</h2><p>${s.text}</p></div><div class="onboard-visual onboard-step">${s.visual}</div>`;const back=q('.onboard-back',root);back.hidden=idx===0;q('.onboard-next',root).textContent=idx===steps.length-1?'Бастау →':'Таныстым →'}
  function close(done=true){if(!root)return;if(done)localStorage.setItem(KEY,'done');root.classList.remove('show');document.body.classList.remove('juz-onboarding-open');setTimeout(()=>{root?.remove();root=null},220)}
  function open(force=false){if(!force&&localStorage.getItem(KEY)==='done')return;if((location.pathname.split('/').pop()||'index.html').toLowerCase()!=='index.html'&&!force)return;if(!localStorage.getItem('juzderek_username')&&!force)return;ensureCss();if(root){root.classList.add('show');return}idx=0;root=document.createElement('div');root.className='juz-onboarding';root.innerHTML=`<section class="juz-onboarding-board" role="dialog" aria-modal="true" aria-label="JUZDEREK-пен танысу"><div class="onboard-top"><div class="onboard-brand"><img src="./assets/logo-mark.webp" alt="">JUZDEREK</div><div class="onboard-count"></div></div><div class="onboard-progress"><span></span></div><div class="onboard-body"></div><div class="onboard-actions"><button class="onboard-back" type="button">← Артқа</button><div><button class="onboard-skip" type="button">Өткізіп жіберу</button><button class="onboard-next" type="button"></button></div></div></section>`;document.body.appendChild(root);document.body.classList.add('juz-onboarding-open');q('.onboard-back',root).onclick=()=>{if(idx>0){idx--;render()}};q('.onboard-next',root).onclick=()=>{if(idx<steps.length-1){idx++;render()}else close(true)};q('.onboard-skip',root).onclick=()=>close(true);render();requestAnimationFrame(()=>root.classList.add('show'))}
  window.JUZ_ONBOARDING={open,reset:()=>{localStorage.removeItem(KEY);open(true)}};
  function auto(){if(document.readyState==='loading')return;setTimeout(()=>open(false),280)}
  document.addEventListener('juzderek:username-ready',()=>setTimeout(()=>open(false),180));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',auto);else auto();
})();