(()=>{
const TRACKER='juzderek_topic_tracker_v1',GAME='juzderek_topics_progress',MODES=['cards','quiz','person','chrono'];
const read=(k,d={})=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const slug=s=>String(s).toLowerCase().replace(/[^a-zа-яәіңғүұқөһ0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,90);
const idFor=name=>window.JUZDEREK_TOPIC_ALIASES?.[name]||`plan-${slug(name)}`;
function mission(){const host=document.getElementById('trackerMission');if(!host)return;const recent=read('juzderek_recent_activity',[]),today=new Date().toISOString().slice(0,10),done=Math.min(4,(Array.isArray(recent)?recent:[]).filter(x=>String(x?.at||x?.date||'').slice(0,10)===today).length);host.innerHTML=`<div class="mission-mini-icon">🎯</div><div><small>Бүгінгі миссия</small><strong>${done} / 4</strong><span>Миссияларды көру</span></div><a href="periods.html#dailyMission" aria-label="Бүгінгі миссия">›</a>`}
function status(id){const r=read(TRACKER,{})[id]||{},g=read(GAME,{})[id]||{};if(r.manualStatus)return r.manualStatus;const done=[...new Set(Array.isArray(g.completed)?g.completed:[])],count=MODES.filter(x=>done.includes(x)).length;const vals=[g.average,g.accuracy,g.percent,g.score].map(Number).filter(Number.isFinite),best=vals.length?Math.max(...vals):0;if(count>=4&&best>=90)return'mastered';if(count>=4)return'reinforced';if(r.readAt)return'read';return'unread'}
function allTopics(){const labels={ancient:'Ежелгі кезең',medieval:'Орта ғасырлар',modern:'Жаңа заман',contemporary:'Қазіргі заман'},out=[];for(const era of Object.keys(labels)){for(const chapter of window.JUZDEREK_CHAPTER_MAP?.[era]||[]){for(const name of chapter[2]||[]){if(name==='Құбылай мемлекеті, Ильханат')continue;out.push({id:idFor(name),name,era,label:labels[era]})}}}return out}
function showToast(text){let t=document.getElementById('trackerToast');if(!t){t=document.createElement('div');t.id='trackerToast';t.className='tracker-toast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1800)}
function markReview(id){if(!id)return;const all=read(TRACKER,{}),r=all[id]||{},now=new Date().toISOString(),first=!r.readAt;if(first)r.readAt=now;else{r.lastReviewAt=now;r.reviewCount=(Number(r.reviewCount)||0)+1}all[id]=r;localStorage.setItem(TRACKER,JSON.stringify(all));window.dispatchEvent(new CustomEvent('juzderek:tracker'));showToast(first?'Тақырып оқылды ✓':`Қайталанды ✓ · ${r.reviewCount} рет`)}
function periodStats(days){const data=read(TRACKER,{}),cut=Date.now()-days*86400000;let readCount=0,reviewCount=0;for(const r of Object.values(data)){if(r.readAt&&new Date(r.readAt).getTime()>=cut)readCount++;if(r.lastReviewAt&&new Date(r.lastReviewAt).getTime()>=cut)reviewCount++}return{readCount,reviewCount}}
function renderStatsPeriod(modal,days,label){const topics=allTopics(),counts={unread:0,read:0,reinforced:0,mastered:0};topics.forEach(t=>counts[status(t)]++);const p=periodStats(days),done=topics.length-counts.unread,pct=topics.length?Math.round(done/topics.length*100):0;const byEra={};topics.forEach(t=>(byEra[t.era]??=[]).push(t));modal.querySelector('[data-stats-body]').innerHTML=`<div class="stats-summary"><div><span>Оқылған тақырып</span><strong>${p.readCount}</strong></div><div><span>Қайталау саны</span><strong>${p.reviewCount}</strong></div><div><span>Бекітілген</span><strong>${counts.reinforced}</strong></div><div><span>Меңгерілген</span><strong>${counts.mastered}</strong></div></div><div class="stats-period-note">${label} · Жалпы прогресс ${pct}%</div><div class="stats-era-list">${Object.entries(byEra).map(([era,arr])=>{const d=arr.filter(t=>status(t)!=='unread').length,p=arr.length?Math.round(d/arr.length*100):0;return `<div class="stats-era-row"><div><b>${arr[0]?.label||era}</b><span>${d} / ${arr.length} тақырып</span></div><strong>${p}%</strong><i><em style="width:${p}%"></em></i></div>`}).join('')}</div>`}
function openStats(){let modal=document.getElementById('trackerStatsModal');if(!modal){modal=document.createElement('div');modal.id='trackerStatsModal';modal.className='tracker-stats-modal';modal.innerHTML=`<div class="tracker-stats-card"><button type="button" class="tracker-stats-close" data-stats-close>×</button><h2>Статистика</h2><div class="stats-tabs"><button class="active" data-days="7" data-label="Осы апта">Апта</button><button data-days="30" data-label="Осы ай">Ай</button><button data-days="365" data-label="Осы жыл">Жыл</button></div><div data-stats-body></div></div>`;document.body.appendChild(modal)}modal.classList.add('show');const active=modal.querySelector('.stats-tabs .active');renderStatsPeriod(modal,Number(active?.dataset.days||7),active?.dataset.label||'Осы апта')}
function bind(){document.addEventListener('click',e=>{const stats=e.target.closest('[data-scroll-stats]');if(stats){e.preventDefault();openStats();return}const close=e.target.closest('[data-stats-close]');if(close||e.target.id==='trackerStatsModal'){document.getElementById('trackerStatsModal')?.classList.remove('show');return}const tab=e.target.closest('.stats-tabs [data-days]');if(tab){const m=document.getElementById('trackerStatsModal');m.querySelectorAll('.stats-tabs button').forEach(b=>b.classList.toggle('active',b===tab));renderStatsPeriod(m,Number(tab.dataset.days),tab.dataset.label);return}},false);
document.addEventListener('click',e=>{const b=e.target.closest('[data-read]');if(!b||!document.querySelector('.tracker-shell'))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();markReview(b.dataset.read)},true)}
function addLegendDots(){document.querySelectorAll('#overallProgress .legend div').forEach((row,i)=>{if(row.querySelector('.legend-dot'))return;const cls=['unread','read','reinforced','mastered'][i];const d=document.createElement('i');d.className=`legend-dot ${cls}`;row.prepend(d)})}
function sync(){mission();requestAnimationFrame(addLegendDots)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{sync();bind()});else{sync();bind()}window.addEventListener('storage',sync);window.addEventListener('juzderek:progress',sync);window.addEventListener('juzderek:tracker',sync);
})();