(()=>{
const STORE='juzderek_topic_tracker_v1',GAME='juzderek_topics_progress',ALL_MODES=['cards','quiz','person','chrono'],PERSONLESS=new Set(['new-era-overview']);
const ERA_LABEL={ancient:'Ежелгі кезең',medieval:'Орта ғасырлар',modern:'Жаңа заман',contemporary:'Қазіргі заман'},ERA_ORDER=['ancient','medieval','modern','contemporary'];
const ICON={unread:'○',read:'✓',reinforced:'★',mastered:'🏆'},LABEL={unread:'Оқылмаған',read:'Оқылды',reinforced:'Бекітілді',mastered:'Меңгерілді'};
const read=(k,d={})=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}},save=v=>localStorage.setItem(STORE,JSON.stringify(v));
const slug=s=>String(s).toLowerCase().replace(/[^a-zа-яәіңғүұқөһ0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,90);function tracker(){return read(STORE,{})}function games(){return read(GAME,{})}function idFor(name){return window.JUZDEREK_TOPIC_ALIASES?.[name]||`plan-${slug(name)}`}function requiredModes(id){return PERSONLESS.has(id)?['cards','quiz','chrono']:ALL_MODES}
function flatten(){const map=window.JUZDEREK_CHAPTER_MAP||{},out=[];for(const era of ERA_ORDER)for(const chapter of map[era]||[])for(const name of chapter[2]||[]){if(name==='Құбылай мемлекеті, Ильханат')continue;const id=idFor(name);out.push({id,name,era,eraLabel:ERA_LABEL[era],chapter:chapter[1],ready:!!window.JUZDEREK_TOPIC_INDEX?.[id]?.ready})}return out}
function gameInfo(id){const g=games()[id]||{},done=[...new Set(Array.isArray(g.completed)?g.completed:[])],req=requiredModes(id),pcts=req.map(m=>Number(g.scores?.[m]?.pct)).filter(Number.isFinite),avg=pcts.length?pcts.reduce((a,b)=>a+b,0)/pcts.length:0;return{done:req.filter(x=>done.includes(x)).length,total:req.length,complete:req.every(x=>done.includes(x)),avg}}
function status(topic){const rec=tracker()[topic.id]||{},g=gameInfo(topic.id);if(rec.manualStatus)return rec.manualStatus;if(g.complete&&g.avg>=90)return'mastered';if(g.complete)return'reinforced';if(rec.readAt)return'read';return'unread'}
function markRead(id,asReview=false){const all=tracker(),r=all[id]||{},now=new Date().toISOString();if(!r.readAt)r.readAt=now;else if(asReview||r.readAt){r.lastReviewAt=now;r.reviewCount=(Number(r.reviewCount)||0)+1}all[id]=r;save(all);render();dispatchEvent(new CustomEvent('juzderek:tracker'))}
function setStatus(id,st){const all=tracker(),r=all[id]||{};r.manualStatus=st==='unread'?null:st;if(st!=='unread'&&!r.readAt)r.readAt=new Date().toISOString();if(st==='unread'){delete r.readAt;delete r.lastReviewAt;r.reviewCount=0}all[id]=r;save(all);render();dispatchEvent(new CustomEvent('juzderek:tracker'))}
const fmt=iso=>{if(!iso)return'';const d=new Date(iso);return d.toLocaleDateString('kk-KZ',{day:'numeric',month:'short'})+', '+d.toLocaleTimeString('kk-KZ',{hour:'2-digit',minute:'2-digit'})},ageDays=iso=>iso?Math.floor((Date.now()-new Date(iso).getTime())/86400000):0;let filter='all',query='',openEra='medieval',selected=null;
function stats(topics){const c={unread:0,read:0,reinforced:0,mastered:0};topics.forEach(t=>c[status(t)]++);return c}
function renderStats(topics){const c=stats(topics);document.getElementById('trackerStats').innerHTML=`<article class="tracker-stat"><div class="ico">📖</div><div><small>Барлық тақырып</small><strong>${topics.length}</strong></div></article><article class="tracker-stat"><div class="ico">✓</div><div><small>Оқылған</small><strong>${c.read}</strong></div></article><article class="tracker-stat"><div class="ico">★</div><div><small>Бекітілген</small><strong>${c.reinforced}</strong></div></article><article class="tracker-stat"><div class="ico">🏆</div><div><small>Меңгерілген</small><strong>${c.mastered}</strong></div></article>`}
function topicRow(t){const st=status(t),r=tracker()[t.id]||{},when=r.lastReviewAt||r.readAt,action=st==='unread'?'Оқып шықтым':'Қайталадым';return `<div class="topic-row" data-id="${t.id}"><span class="status-dot ${st}">${ICON[st]}</span><button class="topic-name open-topic" data-id="${t.id}" style="border:0;background:transparent;text-align:left;padding:0;cursor:pointer">${t.name}</button><div class="topic-time">${st==='unread'?'':`${LABEL[st]}<br>${fmt(when)}`}</div><button class="topic-action ${st==='unread'?'':'reviewed'}" data-read="${t.id}">${action}</button><button class="topic-menu open-topic" data-id="${t.id}">›</button></div>`}
function renderGroups(topics){const host=document.getElementById('trackerGroups'),byEra={};topics.forEach(t=>(byEra[t.era]??=[]).push(t));let html='';for(const era of ERA_ORDER){const arr=byEra[era]||[],visible=arr.filter(t=>(filter==='all'||status(t)===filter)&&(!query||t.name.toLowerCase().includes(query)));if(!visible.length&&query)continue;const done=arr.filter(t=>status(t)!=='unread').length,pct=arr.length?Math.round(done/arr.length*100):0,opened=openEra===era||!!query;html+=`<div class="era-block"><button class="era-head" data-era="${era}"><strong>${ERA_LABEL[era]}</strong><span class="era-meta">${done} / ${arr.length} тақырып</span><span class="era-progress"><span style="width:${pct}%"></span></span><span class="era-pct">${pct}%</span><span>${opened?'⌃':'⌄'}</span></button><div class="era-topics" ${opened?'':'hidden'}>${visible.length?visible.map(topicRow).join(''):'<div class="empty-state">Бұл фильтр бойынша тақырып жоқ.</div>'}</div></div>`}host.innerHTML=html||'<div class="empty-state">Тақырып табылмады.</div>'}
function renderReviews(topics){const items=topics.filter(t=>status(t)!=='unread').map(t=>{const r=tracker()[t.id]||{},last=r.lastReviewAt||r.readAt;return{...t,days:ageDays(last)}}).sort((a,b)=>b.days-a.days).slice(0,3);document.getElementById('reviewSuggestions').innerHTML=items.length?items.map(t=>`<div class="review-item"><span class="review-dot"></span><div><b>${t.name}</b><small>${t.days===0?'Бүгін':t.days+' күн бұрын'}</small></div><button data-read="${t.id}">Қайталау</button></div>`).join(''):'<div class="empty-state">Әзірге қайталау ұсынысы жоқ.</div>'}
function renderWeek(){const all=tracker(),days=['Дс','Сс','Ср','Бс','Жм','Сн','Жк'],now=new Date(),monday=new Date(now),day=(now.getDay()+6)%7;monday.setHours(0,0,0,0);monday.setDate(now.getDate()-day);const counts=Array(7).fill(0);for(const r of Object.values(all))for(const iso of [r.readAt,r.lastReviewAt]){if(!iso)continue;const d=new Date(iso),idx=Math.floor((d-monday)/86400000);if(idx>=0&&idx<7)counts[idx]++}const max=Math.max(1,...counts);document.getElementById('weekTotal').textContent=counts.reduce((a,b)=>a+b,0);document.getElementById('weekBars').innerHTML=counts.map((n,i)=>`<div class="daybar ${n?'active':''}"><i style="height:${Math.max(8,n/max*76)}px"></i><span>${days[i]}</span></div>`).join('')}
function renderOverall(topics){const c=stats(topics),done=topics.length-c.unread,pct=topics.length?Math.round(done/topics.length*100):0;document.getElementById('overallProgress').innerHTML=`<div class="overall-wrap"><div class="donut" style="--p:${pct}"><strong>${pct}%</strong></div><div class="legend"><div><span>Оқылмаған</span><b>${c.unread}</b></div><div><span>Оқылған</span><b>${c.read}</b></div><div><span>Бекітілген</span><b>${c.reinforced}</b></div><div><span>Меңгерілген</span><b>${c.mastered}</b></div></div></div>`}
function modal(t){selected=t;const st=status(t),r=tracker()[t.id]||{},last=r.lastReviewAt||r.readAt,gi=gameInfo(t.id),host=document.getElementById('trackerModal');host.hidden=false;host.innerHTML=`<div class="modal-card"><button class="modal-close" data-close>×</button><div class="modal-status">${ICON[st]}</div><h2>${t.name}</h2><div class="modal-sub">${LABEL[st]}${last?' · '+fmt(last):''}${gi.done?` · ${gi.done}/${gi.total} ойын`:''}</div><div class="modal-actions"><button class="modal-review" data-read="${t.id}">${st==='unread'?'Оқып шықтым':'↻ Қайталадым'}</button>${t.ready?`<button class="modal-games" data-games="${t.id}">Ойындар ойнау</button>`:'<button class="modal-games" disabled>Контент кейін қосылады</button>'}</div><div class="status-steps">${['unread','read','reinforced','mastered'].map(s=>`<div class="status-step ${s===st?'active':''}"><button data-status="${s}" data-id="${t.id}"><b>${ICON[s]}</b>${LABEL[s]}</button></div>`).join('')}</div></div>`}
function render(){const topics=flatten();renderStats(topics);renderGroups(topics);renderReviews(topics);renderWeek();renderOverall(topics);if(selected){const t=topics.find(x=>x.id===selected.id);if(t)modal(t)}}
document.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===f));render();return}const eh=e.target.closest('[data-era]');if(eh){openEra=openEra===eh.dataset.era?'':eh.dataset.era;render();return}const r=e.target.closest('[data-read]');if(r){markRead(r.dataset.read,status(flatten().find(t=>t.id===r.dataset.read))!=='unread');return}const o=e.target.closest('.open-topic');if(o){const t=flatten().find(x=>x.id===o.dataset.id);if(t)modal(t);return}if(e.target.closest('[data-close]')||e.target.id==='trackerModal'){document.getElementById('trackerModal').hidden=true;selected=null;return}const s=e.target.closest('[data-status]');if(s){setStatus(s.dataset.id,s.dataset.status);return}const g=e.target.closest('[data-games]');if(g)location.href=`games.html?topic=${encodeURIComponent(g.dataset.games)}&mode=cards`});
document.getElementById('topicSearch').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();renderGroups(flatten())});window.addEventListener('storage',e=>{if([STORE,GAME].includes(e.key))render()});window.addEventListener('juzderek:progress',render);window.addEventListener('juzderek:tracker',render);render();
})();